// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { BranchRemoteNode } from '../../providers/branchTreeProvider';

export function asBranchRemoteItem(this: CommandController, value: unknown): BranchRemoteNode | undefined {
  return value instanceof BranchRemoteNode ? value : undefined;
}
