// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { BranchTreeItem } from '../../providers/branchTreeProvider';

export function asBranchItem(this: CommandController, value: unknown): BranchTreeItem | undefined {
  return value instanceof BranchTreeItem ? value : undefined;
}
