// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { CommitRangeFileTreeItem } from '../../providers/commitFilesTreeProvider';

export function asCommitRangeFileItem(this: CommandController, value: unknown): | { filePath: string; fromRef: string; toRef: string; fromLabel: string; toLabel: string }
    | undefined {
  if (value instanceof CommitRangeFileTreeItem) {
        return {
          filePath: value.filePath,
          fromRef: value.fromRef,
          toRef: value.toRef,
          fromLabel: value.fromLabel,
          toLabel: value.toLabel
        };
      }
  
      if (
        typeof value === 'object' &&
        value !== null &&
        'filePath' in value &&
        'fromRef' in value &&
        'toRef' in value
      ) {
        const record = value as Record<string, unknown>;
        if (
          typeof record.filePath === 'string' &&
          typeof record.fromRef === 'string' &&
          typeof record.toRef === 'string'
        ) {
          return {
            filePath: record.filePath,
            fromRef: record.fromRef,
            toRef: record.toRef,
            fromLabel: typeof record.fromLabel === 'string' ? record.fromLabel : record.fromRef,
            toLabel: typeof record.toLabel === 'string' ? record.toLabel : record.toRef
          };
        }
      }
  
      return undefined;
}
