// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { CommitFileTreeItem } from '../../providers/commitFilesTreeProvider';

export function asCommitViewFileItem(this: CommandController, value: unknown): CommitFileTreeItem | undefined {
  return value instanceof CommitFileTreeItem ? value : undefined;
}
