// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export function asFileResourceUri(this: CommandController, value: unknown): vscode.Uri | undefined {
  if (value instanceof vscode.Uri) {
        return value.scheme === 'file' ? value : undefined;
      }
  
      if (
        typeof value === 'object' &&
        value !== null &&
        'resourceUri' in value &&
        (value as { resourceUri?: unknown }).resourceUri instanceof vscode.Uri
      ) {
        const uri = (value as { resourceUri: vscode.Uri }).resourceUri;
        return uri.scheme === 'file' ? uri : undefined;
      }
  
      return undefined;
}
