// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { GraphCommitFileTreeItem } from '../../providers/graphTreeProvider';

export function asGraphFileItem(this: CommandController, value: unknown): GraphCommitFileTreeItem | undefined {
  return value instanceof GraphCommitFileTreeItem ? value : undefined;
}
