// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { GraphCommitTreeItem } from '../../providers/graphTreeProvider';

export function asGraphItem(this: CommandController, value: unknown): GraphCommitTreeItem | undefined {
  return value instanceof GraphCommitTreeItem ? value : undefined;
}
