// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { RevisionFileTreeItem } from '../../providers/commitFilesTreeProvider';

export function asRevisionViewFileItem(this: CommandController, value: unknown): RevisionFileTreeItem | undefined {
  return value instanceof RevisionFileTreeItem ? value : undefined;
}
