// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { StashTreeItem } from '../../providers/stashTreeProvider';

export function asStashItem(this: CommandController, value: unknown): StashTreeItem | undefined {
  return value instanceof StashTreeItem ? value : undefined;
}
