// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { TagTreeItem } from '../../providers/branchTreeProvider';

export function asTagItem(this: CommandController, value: unknown): TagTreeItem | undefined {
  return value instanceof TagTreeItem ? value : undefined;
}
