// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { WorkingTreeCompareFileTreeItem } from '../../providers/commitFilesTreeProvider';

export function asWorkingTreeCompareFileItem(this: CommandController, value: unknown): { filePath: string; ref: string; refLabel: string; status: string } | undefined {
  if (value instanceof WorkingTreeCompareFileTreeItem) {
        return {
          filePath: value.filePath,
          ref: value.ref,
          refLabel: value.refLabel,
          status: value.status
        };
      }
  
      if (
        typeof value === 'object' &&
        value !== null &&
        'filePath' in value &&
        'ref' in value &&
        'refLabel' in value &&
        'status' in value
      ) {
        const record = value as Record<string, unknown>;
        if (
          typeof record.filePath === 'string' &&
          typeof record.ref === 'string' &&
          typeof record.refLabel === 'string' &&
          typeof record.status === 'string'
        ) {
          return {
            filePath: record.filePath,
            ref: record.ref,
            refLabel: record.refLabel,
            status: record.status
          };
        }
      }
  
      return undefined;
}
