// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { RebaseIssueKind } from '../types';

export function classifyRebaseIssue(this: CommandController, error: unknown): { kind: RebaseIssueKind; message?: string } {
  const message = this.getErrorSummary(error);
      const normalized = message.toLowerCase();
  
      const conflictMarkers = [
        'conflict',
        'could not apply',
        'unmerged files',
        'resolve all conflicts manually',
        'after resolving the conflicts',
        'fix conflicts and then run'
      ];
      if (conflictMarkers.some((marker) => normalized.includes(marker))) {
        return { kind: 'conflict', message };
      }
  
      return { kind: 'failed', message };
}
