// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { CherryPickIssueKind } from '../types';

export function classifyCherryPickIssue(this: CommandController, error: unknown): { kind: CherryPickIssueKind; message?: string } {
  const message = this.getErrorSummary(error);
      const normalized = message.toLowerCase();
  
      const emptyMarkers = [
        'nothing to cherry-pick',
        'the previous cherry-pick is now empty',
        'nothing to commit, working tree clean',
        'the patch is empty'
      ];
      if (emptyMarkers.some((marker) => normalized.includes(marker))) {
        return { kind: 'nothingToCherryPick', message };
      }
  
      const conflictMarkers = [
        'conflict',
        'could not apply',
        'unmerged files',
        'cannot cherry-pick',
        'can not cherry pick',
        'after resolving the conflicts',
        'fix conflicts and then commit the result',
        'cherry-pick failed'
      ];
      if (conflictMarkers.some((marker) => normalized.includes(marker))) {
        return { kind: 'conflict', message };
      }
  
      return { kind: 'failed', message };
}
