// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { MergeIssueKind } from '../types';

export function classifyMergeIssue(this: CommandController, error: unknown): { kind: MergeIssueKind; message?: string } {
  const message = this.getErrorSummary(error);
      const normalized = message.toLowerCase();
  
      const conflictMarkers = [
        'conflict',
        'automatic merge failed',
        'unmerged files',
        'fix conflicts and then commit the result',
        'merge failed'
      ];
      if (conflictMarkers.some((marker) => normalized.includes(marker))) {
        return { kind: 'conflict', message };
      }
  
      return { kind: 'failed', message };
}
