// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { CommitFileTreeItem, CommitFolderTreeItem, CommitRangeFileTreeItem, WorkingTreeCompareFileTreeItem } from '../../providers/commitFilesTreeProvider';
import { GraphCommitFileTreeItem } from '../../providers/graphTreeProvider';
import { SelectableChangeTreeItem } from '../types';

export function extractSelectableItem(this: CommandController, value: unknown): SelectableChangeTreeItem | undefined {
  if (value instanceof GraphCommitFileTreeItem) {
        return value;
      }
      if (value instanceof CommitFileTreeItem) {
        return value;
      }
      if (value instanceof CommitRangeFileTreeItem) {
        return value;
      }
      if (value instanceof WorkingTreeCompareFileTreeItem) {
        return value;
      }
      if (value instanceof CommitFolderTreeItem) {
        return value;
      }
      return undefined;
}
