// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export function getActiveFilePath(this: CommandController): string | undefined {
  const editor = vscode.window.activeTextEditor;
      const uri = editor?.document.uri;
      if (!uri || uri.scheme !== 'file') {
        return undefined;
      }
  
      return this.git.toRepoRelative(uri.fsPath);
}
