// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function handleRefresh(this: CommandController): Promise<void> {
  await this.state.refreshVisible();
      void vscode.window.setStatusBarMessage('VS Code Git Client refreshed', 1500);
}
