// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';
import { GitCommand } from '../../config/commands';
import { GraphFilterView } from '../../views/graphFilterView';

export async function handleGraphClearFilter(this: CommandController): Promise<void> {
  await GraphFilterView.clearCurrentFilters();
      await vscode.commands.executeCommand('setContext', GitCommand.GraphFilterActive, false);
}
