// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';
import { SubmoduleTreeItem } from '../../providers/submoduleTreeProvider';

export async function handleSubmoduleDiffPointer(this: CommandController, arg?: unknown): Promise<void> {
  const item = arg instanceof SubmoduleTreeItem ? arg : undefined;
      if (!item) {
        return;
      }
      const diff = await this.git.getSubmodulePointerDiff(item.submodule.path);
      if (!diff.trim()) {
        void vscode.window.showInformationMessage('No pointer diff for this submodule.');
        return;
      }
      const doc = await vscode.workspace.openTextDocument({ content: diff, language: 'diff' });
      await vscode.window.showTextDocument(doc);
}
