// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleBranchTrack(this: CommandController, arg?: unknown): Promise<void> {
  const local =
        this.toBranchName(arg) ?? (await this.pickBranchName('Pick local branch to track'));
      if (!local) {
        return;
      }
  
      const remote = await this.pickBranchName('Pick remote upstream branch', true);
      if (!remote) {
        return;
      }
  
      await this.git.trackBranch(local, remote);
      await this.state.refreshAll();
}
