// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { confirmDangerousAction } from '../../guards';

export async function handleBranchMergeIntoCurrent(this: CommandController, arg?: unknown): Promise<void> {
  const branch =
        this.toBranchName(arg) ??
        (await this.pickBranchName('Pick branch to merge into current branch'));
      if (!branch) {
        return;
      }
  
      const confirmed = await confirmDangerousAction({
        title: 'Merge into current branch',
        detail: `Source branch: ${branch}`,
        acceptLabel: 'Merge'
      });
      if (!confirmed) {
        return;
      }
  
      await this.startMergeOperation(() => this.git.mergeIntoCurrent(branch));
}
