// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';
import { confirmDangerousAction } from '../../guards';

export async function handleOperationAbort(this: CommandController): Promise<void> {
  const state = await this.git.getOperationState();
      if (state.kind === 'none') {
        void vscode.window.showInformationMessage('No merge/rebase/cherry-pick/revert in progress.');
        return;
      }
      const confirmed = await confirmDangerousAction({
        title: `Abort ${state.kind}`,
        detail: 'This will reset the working tree to before the operation started.',
        acceptLabel: 'Abort'
      });
      if (!confirmed) {
        return;
      }
      try {
        if (state.kind === 'merge') {
          await this.git.mergeAbort();
        } else if (state.kind === 'rebase') {
          await this.git.rebaseAbort();
        } else if (state.kind === 'cherry-pick') {
          await this.git.cherryPickAbort();
        } else if (state.kind === 'revert') {
          await this.git.revertAbort();
        }
      } finally {
        await this.state.refreshAll();
      }
}
