// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { confirmDangerousAction } from '../../guards';

export async function handleGraphRebaseInteractiveFromHere(this: CommandController, arg?: unknown): Promise<void> {
  const base =
        this.toCommitSha(arg) ??
        (await this.pickCommitSha('Pick base commit for interactive rebase'));
      if (!base) {
        return;
      }
  
      const confirmed = await confirmDangerousAction({
        title: 'Interactive rebase',
        detail: `Base commit: ${base}`,
        acceptLabel: 'Start rebase'
      });
      if (!confirmed) {
        return;
      }
  
      await this.startRebaseOperation(() => this.git.rebaseInteractive(base));
}
