// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function handleTagCopyRevisionNumber(this: CommandController, arg?: unknown): Promise<void> {
  const revision = this.toTagRevision(arg) ?? (await this.pickCommitSha('Pick revision to copy'));
      if (!revision) {
        return;
      }
  
      await vscode.env.clipboard.writeText(revision);
      void vscode.window.setStatusBarMessage(`Copied ${revision}`, 1500);
}
