// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';
import { confirmDangerousAction } from '../../guards';

export async function handleRevertSelectedChanges(this: CommandController, arg?: unknown, selected?: unknown): Promise<void> {
  const target = await this.resolveSelectedCommitFiles(arg, selected);
      if (!target) {
        void vscode.window.showInformationMessage('Select one or more files from a commit first.');
        return;
      }
  
      if (!target.canRevert) {
        void vscode.window.showWarningMessage(
          'Selected files cannot be reverted from the current branch.'
        );
        return;
      }
  
      const confirmed = await confirmDangerousAction({
        title: 'Revert selected changes',
        detail: `${target.detailLabel}\nFiles: ${target.filePaths.length}\n${target.filePaths.map((path) => `- ${path}`).join('\n')}`,
        acceptLabel: 'Revert'
      });
      if (!confirmed) {
        return;
      }
  
      if (target.kind === 'commit') {
        await this.git.revertCommitFiles(target.sha, target.filePaths);
      } else if (target.kind === 'range') {
        const patch = await this.git.getPatchBetweenRefsForFiles(
          target.fromRef,
          target.toRef,
          target.filePaths
        );
        await this.git.reverseApplyPatchToWorkingTree(patch);
      } else {
        const patch = await this.git.getPatchBetweenWorkingTreeAndRefForFiles(
          target.ref,
          target.filePaths
        );
        await this.git.reverseApplyPatchToWorkingTree(patch);
      }
      await this.state.refreshAll();
      void vscode.window.showInformationMessage(
        `Reverted selected changes from ${target.shortLabel} in the current checkout.`
      );
}
