// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function handleConflictResolve(this: CommandController, arg?: unknown, mode?: 'ours' | 'theirs' | 'both'): Promise<void> {
  const pickTitles: Record<'ours' | 'theirs' | 'both', string> = {
        ours: 'Accept Yours (ours) for which file?',
        theirs: 'Accept Theirs for which file?',
        both: 'Accept Both: open merge editor for which file?'
      };
      const path =
        this.pickConflictPathArg(arg) ?? (await this.pickConflictPath(pickTitles[mode ?? 'ours']));
      if (!path) {
        return;
      }
  
      switch (mode) {
        case 'ours':
          await this.git.resolveConflictOurs(path);
          await this.state.refreshChanges();
          void vscode.window.showInformationMessage(`Accepted yours: ${path}`);
          break;
        case 'theirs':
          await this.git.resolveConflictTheirs(path);
          await this.state.refreshChanges();
          void vscode.window.showInformationMessage(`Accepted theirs: ${path}`);
          break;
        case 'both':
          await this.editor.openMergeConflict(path);
          break;
      }
}
