// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { confirmDangerousAction } from '../../guards';

export async function handleGitPullWithPreview(this: CommandController): Promise<void> {
  const preview = await this.git.getOutgoingIncomingPreview();
      const confirmed = await confirmDangerousAction({
        title: 'Pull current branch',
        detail: `Incoming commits:\n${preview.incoming.slice(0, 10).join('\n') || 'none'}`,
        acceptLabel: 'Pull'
      });
      if (!confirmed) {
        return;
      }
  
      await this.git.pull();
      await this.state.refreshAll();
}
