// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleOpenFileDiff(this: CommandController, arg?: unknown, selected?: unknown): Promise<void> {
  if (await this.openSelectedFileDiffs(arg, selected)) {
        return;
      }
  
      const item = this.asGraphFileItem(arg);
      if (item) {
        await this.editor.openCommitFileDiffWithStatus(item.commit.sha, item.filePath, item.status, {
          oldPath: item.oldPath
        });
        return;
      }
  
      const rangeItem = this.asCommitRangeFileItem(arg);
      if (rangeItem) {
        await this.editor.openCommitRangeFileDiff(
          rangeItem.fromRef,
          rangeItem.toRef,
          rangeItem.filePath,
          { fromLabel: rangeItem.fromLabel, toLabel: rangeItem.toLabel }
        );
        return;
      }
  
      const commitItem = this.asCommitViewFileItem(arg);
      if (!commitItem) {
        return;
      }
  
      await this.editor.openCommitFileDiffWithStatus(
        commitItem.sha,
        commitItem.filePath,
        commitItem.status
      );
}
