// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleGitSshPullBitbucket(this: CommandController): Promise<void> {
  await this.sshPull('bitbucket.org');
}
