// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleGraphOpenCommitRangeDetails(this: CommandController, arg?: unknown, selected?: unknown): Promise<void> {
  const selectedShas = this.toGraphCommitShas(arg, selected);
      if (selectedShas.length < 2) {
        return;
      }
      await this.editor.openCommitRangeDetails(selectedShas);
}
