// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { confirmDangerousAction } from '../../guards';

export async function handleEditCommitMessage(this: CommandController, arg?: unknown): Promise<void> {
  const sha = this.toCommitSha(arg) ?? (await this.pickCommitSha('Pick commit to edit message'));
  if (!sha) {
    return;
  }

  const details = await this.git.getCommitDetails(sha);
  if (!details.commit.subject) {
    void vscode.window.showErrorMessage(
      `Unable to load commit message for ${sha.slice(0, 8)}.`
    );
    return;
  }
  const currentMessage = details.commit.subject.trim();
  const nextMessage = await vscode.window.showInputBox({
    title: `Edit commit message (${sha.slice(0, 8)})`,
    value: currentMessage,
    validateInput: (value) => (value.trim() ? undefined : 'Commit message is required')
  });
  if (nextMessage === undefined) {
    return;
  }

  const trimmedMessage = nextMessage.trim();
  if (trimmedMessage === currentMessage) {
    return;
  }

  const confirmed = await confirmDangerousAction({
    title: 'Rewrite commit message',
    detail: `Commit: ${sha}\nThis rewrites commit history and may require force push.`,
    acceptLabel: 'Rewrite'
  });
  if (!confirmed) {
    return;
  }

  const parent = await this.git.getParentCommit(sha);
  if (!parent) {
    void vscode.window.showWarningMessage(
      'Cannot edit the root commit message from this action.'
    );
    return;
  }

  // Write the new message to a temp file to avoid shell escaping issues
  const messageFile = path.join(os.tmpdir(), `vscode-git-client-edit-msg-${Date.now()}`);
  fs.writeFileSync(messageFile, trimmedMessage, 'utf8');

  try {
    const escapedMessageFile = messageFile.replace(/'/g, "'\\''");
    const escapedSha = sha.replace(/'/g, "'\\''");
    const sequenceEditor = `sh -c 'TODO_FILE="$1"; sed -i.bak -e "s/^pick ${escapedSha}/reword ${escapedSha}/" "$TODO_FILE"; rm -f "$TODO_FILE.bak"' --`;
    const editor = `sh -c 'cat '"'"'${escapedMessageFile}'"'"' > "$1"' --`;

    await this.startRebaseOperation(async () => {
      await this.git.runGit([
        '-c',
        `sequence.editor=${sequenceEditor}`,
        '-c',
        `core.editor=${editor}`,
        'rebase',
        '-i',
        parent
      ]);
    });
  } finally {
    try {
      fs.unlinkSync(messageFile);
    } catch {
      // Ignore cleanup errors
    }
  }
}
