// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleGraphShowRepositoryAtRevision(this: CommandController, arg?: unknown): Promise<void> {
  const sha = this.toCommitSha(arg) ?? (await this.pickCommitSha('Pick revision'));
      if (!sha) {
        return;
      }
  
      await this.editor.showRepositoryAtRevision(sha);
}
