// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';
import { confirmDangerousAction } from '../../guards';

export async function handleCherryPickSelectedChanges(this: CommandController, arg?: unknown, selected?: unknown): Promise<void> {
  const target = await this.resolveSelectedCommitFiles(arg, selected);
      if (!target) {
        void vscode.window.showInformationMessage('Select one or more files from a commit first.');
        return;
      }
  
      if (!target.canCherryPick) {
        void vscode.window.showWarningMessage(
          'Selected files are already available in the current branch.'
        );
        return;
      }
  
      const confirmed = await confirmDangerousAction({
        title: 'Cherry-pick selected changes',
        detail: `${target.detailLabel}\nFiles: ${target.filePaths.length}\n${target.filePaths.map((path) => `- ${path}`).join('\n')}`,
        acceptLabel: 'Cherry-pick'
      });
      if (!confirmed) {
        return;
      }
  
      if (target.kind === 'commit') {
        await this.git.cherryPickCommitFiles(target.sha, target.filePaths);
        const refreshPromise = this.state.refreshAll();
        void vscode.window.showInformationMessage(
          `Cherry-picked selected changes from ${target.shortLabel} into the current checkout.`
        );
        await refreshPromise;
        return;
      }
  
      if (target.kind !== 'range') {
        void vscode.window.showWarningMessage(
          'Selected files are already available in the working tree.'
        );
        return;
      }
  
      const patch = await this.git.getPatchBetweenRefsForFiles(
        target.fromRef,
        target.toRef,
        target.filePaths
      );
      await this.applyPatchToWorkingTree(patch, {
        source: `selected changes from ${target.shortLabel}`
      });
}
