// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { openQuickActions } from './openQuickActions';

export async function handleQuickActions(this: CommandController): Promise<void> {
  await this.openQuickActions();
}
