// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';
import { confirmDangerousAction } from '../../guards';

export async function handleRemoteDelete(this: CommandController, arg?: unknown): Promise<void> {
  const remoteName = this.asBranchRemoteItem(arg)?.remoteName;
      if (!remoteName) {
        return;
      }
  
      const confirmed = await confirmDangerousAction({
        title: 'Delete remote',
        detail: `Remote: ${remoteName}`,
        acceptLabel: 'Delete'
      });
      if (!confirmed) {
        return;
      }
  
      await this.git.deleteRemote(remoteName);
      await this.state.refreshBranches();
      void vscode.window.showInformationMessage(`Deleted remote ${remoteName}.`);
}
