// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';
import { SubmoduleTreeItem } from '../../providers/submoduleTreeProvider';

export async function handleSubmoduleOpenTerminal(this: CommandController, arg?: unknown): Promise<void> {
  const item = arg instanceof SubmoduleTreeItem ? arg : undefined;
      if (!item) {
        return;
      }
      const fullPath = `${this.git.gitRoot}/${item.submodule.path}`;
      const terminal = vscode.window.createTerminal({
        cwd: fullPath,
        name: `Submodule: ${item.submodule.name}`
      });
      terminal.show();
}
