// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';
import { WorktreeTreeItem } from '../../providers/worktreeTreeProvider';

export async function handleWorktreeLock(this: CommandController, arg?: unknown): Promise<void> {
  const item = arg instanceof WorktreeTreeItem ? arg : undefined;
      if (!item) {
        return;
      }
  
      const reason = await vscode.window.showInputBox({
        title: 'Lock reason (optional)',
        placeHolder: 'e.g. long-running experiment'
      });
  
      await this.git.lockWorktree(item.worktree.worktreePath, reason?.trim() || undefined);
      await this.state.refreshWorktrees();
}
