// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleConflictAcceptBoth(this: CommandController, arg?: unknown): Promise<void> {
  await this.handleConflictResolve(arg, 'both');
}
