// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function handleGraphCreatePatchForRange(this: CommandController, arg?: unknown, selected?: unknown): Promise<void> {
  const shas = this.toGraphCommitShas(arg, selected);
      if (shas.length < 2) {
        return;
      }
  
      const patch = await this.git.getPatchForCommitRange(shas);
      const doc = await vscode.workspace.openTextDocument({
        language: 'diff',
        content: patch
      });
      await vscode.window.showTextDocument(doc, { preview: false });
}
