// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { SubmoduleTreeItem } from '../../providers/submoduleTreeProvider';
import { withSubmoduleProgress } from '../helpers/with-submodule-progress';

export async function handleSubmoduleCheckoutRecorded(this: CommandController, arg?: unknown): Promise<void> {
  const item = arg instanceof SubmoduleTreeItem ? arg : undefined;
      if (!item) {
        return;
      }
      try {
        await withSubmoduleProgress(
          this.logger,
          {
            title: `Checking out recorded commit for ${item.submodule.path}…`,
            autoShow: false,
            command: 'Submodule checkout recorded'
          },
          ({ sink, signal }) =>
            this.git.checkoutRecordedSubmoduleCommit(item.submodule.path, { sink, signal })
        );
      } finally {
        await this.state.refreshSubmodules();
      }
}
