// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function handleMergeNext(this: CommandController): Promise<void> {
  await vscode.commands.executeCommand('merge-conflict.next');
}
