// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { confirmDangerousAction } from '../../guards';

export async function handleEditCommitMessage(this: CommandController, arg?: unknown): Promise<void> {
  const sha = this.toCommitSha(arg) ?? (await this.pickCommitSha('Pick commit to edit message'));
  if (!sha) {
    return;
  }

  const isOnCurrentBranch = await this.git.isCommitInCurrentBranch(sha);
  if (!isOnCurrentBranch) {
    void vscode.window.showErrorMessage(
      `Cannot edit commit message: commit ${sha.slice(0, 8)} is not on the current branch. ` +
        'Check out the branch that contains this commit first.'
    );
    return;
  }

  const details = await this.git.getCommitDetails(sha);
  if (!details.commit.subject) {
    void vscode.window.showErrorMessage(
      `Unable to load commit message for ${sha.slice(0, 8)}.`
    );
    return;
  }
  const currentMessage = details.commit.subject.trim();
  const nextMessage = await vscode.window.showInputBox({
    title: `Edit commit message (${sha.slice(0, 8)})`,
    value: currentMessage,
    validateInput: (value) => (value.trim() ? undefined : 'Commit message is required')
  });
  if (nextMessage === undefined) {
    return;
  }

  const trimmedMessage = nextMessage.trim();
  if (trimmedMessage === currentMessage) {
    return;
  }

  const confirmed = await confirmDangerousAction({
    title: 'Rewrite commit message',
    detail: `Commit: ${sha}\nThis rewrites commit history and may require force push.`,
    acceptLabel: 'Rewrite'
  });
  if (!confirmed) {
    return;
  }

  const parent = await this.git.getParentCommit(sha);
  if (!parent) {
    void vscode.window.showWarningMessage(
      'Cannot edit the root commit message from this action.'
    );
    return;
  }

  // Write the new message to a temp file to avoid shell escaping issues
  const messageFile = path.join(os.tmpdir(), `vscode-git-client-edit-msg-${Date.now()}`);
  fs.writeFileSync(messageFile, trimmedMessage, 'utf8');

  try {
    const escapedMessageFile = messageFile.replace(/'/g, "'\\''");
    const escapedSha = sha.replace(/'/g, "'\\''");
    // The rebase todo list abbreviates commit SHAs, so matching the full SHA
    // directly leaves the command as `pick` and makes the rebase a no-op.
    const sequenceEditor = `sh -c 'TODO_FILE="$1"; TARGET_SHA="${escapedSha}"; TODO_TMP="$TODO_FILE.tmp"; while IFS= read -r LINE || [ -n "$LINE" ]; do case "$LINE" in "pick "*) TODO_SHA="\${LINE#pick }"; TODO_SHA="\${TODO_SHA%% *}"; case "$TARGET_SHA" in "$TODO_SHA"*) LINE="reword \${LINE#pick }";; esac;; esac; printf "%s\\n" "$LINE"; done < "$TODO_FILE" > "$TODO_TMP" && mv "$TODO_TMP" "$TODO_FILE"' --`;
    const editor = `sh -c 'cat '"'"'${escapedMessageFile}'"'"' > "$1"' --`;

    await this.startRebaseOperation(async () => {
      await this.git.runGit([
        '-c',
        `sequence.editor=${sequenceEditor}`,
        '-c',
        `core.editor=${editor}`,
        'rebase',
        '-i',
        parent
      ]);
    });
  } finally {
    try {
      fs.unlinkSync(messageFile);
    } catch {
      // Ignore cleanup errors
    }
  }
}
