// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleTagShowRepositoryAtRevision(this: CommandController, arg?: unknown): Promise<void> {
  const revision = this.toTagRevision(arg) ?? (await this.pickCommitSha('Pick revision'));
      if (!revision) {
        return;
      }
      await this.editor.showRepositoryAtRevision(revision);
}
