// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleWorktreeRefresh(this: CommandController): Promise<void> {
  await this.state.refreshWorktrees();
}
