// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';
import { expandTemplate, loadTemplates } from '../../state/commitTemplates';

export async function handleCommitTemplate(this: CommandController): Promise<void> {
  const repository = await this.getBuiltInGitRepository();
      if (!repository) {
        void vscode.window.showWarningMessage('Git repository context not available.');
        return;
      }
  
      const templates = loadTemplates();
      if (templates.length === 0) {
        void vscode.window.showInformationMessage('No commit templates configured.');
        return;
      }
  
      const picked = await vscode.window.showQuickPick(
        templates.map((template) => ({
          label: template.label,
          description: template.template,
          template: template.template
        })),
        {
          title: 'Insert commit message template',
          placeHolder: 'Pick a template'
        }
      );
      if (!picked) {
        return;
      }
  
      let branch = '';
      try {
        branch = await this.git.getCurrentBranch();
      } catch {
        // ignore: branch placeholder will stay empty
      }
  
      const expanded = expandTemplate(picked.template, { branch }).text;
      repository.inputBox.value = expanded;
}
