// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';
import { GitCommand } from '../../config/commands';
import { GraphCommitTreeItem } from '../../providers/graphTreeProvider';

export async function handleGraphGoToChildCommit(this: CommandController, arg?: unknown): Promise<void> {
  const sha = this.toCommitSha(arg) ?? (await this.pickCommitSha('Pick commit'));
      if (!sha) {
        return;
      }
  
      const result = await this.git.runGit(['rev-list', '--children', '-n', '1', sha]);
      const parts = result.stdout.trim().split(/\s+/).filter(Boolean);
      const children = parts.slice(1);
      if (children.length === 0) {
        void vscode.window.showInformationMessage('This commit has no child commit.');
        return;
      }
  
      let child = children[0];
      if (children.length > 1) {
        const picked = await vscode.window.showQuickPick(
          children.map((candidate) => ({ label: candidate })),
          { title: `Pick child commit of ${sha.slice(0, 8)}` }
        );
        if (!picked) {
          return;
        }
        child = picked.label;
      }
  
      const graphCommit = this.state.graph.find((commit) => commit.sha === child);
      if (graphCommit) {
        await vscode.commands.executeCommand(
          GitCommand.GraphOpenDetails,
          new GraphCommitTreeItem(graphCommit)
        );
      } else {
        const subject = (await this.git.getCommitDetails(child)).commit.subject;
        await this.openCommitDetails(child, subject, { openFirstDiff: true });
      }
}
