// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function handleOperationSkip(this: CommandController): Promise<void> {
  const state = await this.git.getOperationState();
      if (state.kind === 'rebase') {
        await this.git.rebaseSkip();
      } else if (state.kind === 'cherry-pick') {
        await this.git.cherryPickSkip();
      } else {
        void vscode.window.showInformationMessage(
          'Skip is only available during rebase or cherry-pick.'
        );
        return;
      }
      await this.state.refreshAll();
}
