// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';
import { confirmDangerousAction } from '../../guards';

export async function handleScmAmendFromInput(this: CommandController): Promise<void> {
  const repository = await this.getBuiltInGitRepository();
      if (!repository) {
        void vscode.window.showWarningMessage('Git repository context not available.');
        return;
      }
  
      const commitMessage = repository.inputBox.value.trim();
      const confirmed = await confirmDangerousAction({
        title: 'Amend last commit',
        detail: commitMessage
          ? 'Use the current Source Control commit message and amend the last commit.'
          : 'Amend the last commit without changing its message.',
        acceptLabel: 'Amend'
      });
      if (!confirmed) {
        return;
      }
  
      await this.git.amendCommit(commitMessage || undefined);
      repository.inputBox.value = '';
      await this.state.refreshAll();
}
