// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';
import { confirmDangerousAction } from '../../guards';
import { WorktreeTreeItem } from '../../providers/worktreeTreeProvider';

export async function handleWorktreeRemove(this: CommandController, arg?: unknown): Promise<void> {
  const item = arg instanceof WorktreeTreeItem ? arg : undefined;
      if (!item) {
        return;
      }
      const { worktree } = item;
  
      if (worktree.isCurrent) {
        void vscode.window.showWarningMessage('Cannot remove the current worktree.');
        return;
      }
  
      if (worktree.isLocked) {
        void vscode.window.showWarningMessage('Unlock the worktree before removing it.');
        return;
      }
  
      if (worktree.isDirty) {
        void vscode.window.showWarningMessage(
          `${worktree.worktreePath} has uncommitted changes. Use Force Remove if you want to discard them.`
        );
        return;
      } else {
        const confirmed = await confirmDangerousAction({
          title: 'Remove worktree',
          detail: worktree.worktreePath,
          acceptLabel: 'Remove'
        });
        if (!confirmed) {
          return;
        }
      }
  
      await this.git.removeWorktree(worktree.worktreePath);
      await this.state.refreshWorktrees();
}
