// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleBranchOpenCommits(this: CommandController, arg?: unknown): Promise<void> {
  const branchName =
        this.toBranchName(arg) ?? (await this.pickBranchName('Pick branch to open commits'));
      if (!branchName) {
        return;
      }
  
      await this.openBranchCommits(branchName);
}
