// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function handleSetRemoteUrl(this: CommandController, arg?: unknown): Promise<void> {
  const remoteItem = this.asBranchRemoteItem(arg);
      const remoteName = remoteItem?.remoteName;
      if (!remoteName) {
        return;
      }
  
      const currentUrl = remoteItem.branches.find((branch) => Boolean(branch.remoteUrl))?.remoteUrl;
      const nextUrl = await vscode.window.showInputBox({
        title: currentUrl
          ? `Change remote URL for ${remoteName}`
          : `Set remote URL for ${remoteName}`,
        value: currentUrl ?? '',
        placeHolder: 'https://github.com/org/repo.git',
        validateInput: (value) => (value.trim() ? undefined : 'Remote URL is required')
      });
      if (!nextUrl) {
        return;
      }
  
      await this.git.setRemoteUrl(remoteName, nextUrl.trim());
      const refreshPromise = this.state.refreshBranches();
      void vscode.window.showInformationMessage(`Remote ${remoteName} URL updated.`);
      await refreshPromise;
}
