// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleStashApplyPop(this: CommandController, arg?: unknown, pop?: boolean): Promise<void> {
  const item = this.asStashItem(arg);
      const ref =
        item?.stash.ref ??
        (await this.pickStashRef(pop ? 'Pick stash to pop' : 'Pick stash to apply'));
      if (!ref) {
        return;
      }
      await this.git.applyStash(ref, !!pop);
      await this.state.refreshAll();
}
