// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleStashApply(this: CommandController, arg?: unknown): Promise<void> {
  await this.handleStashApplyPop(arg, false);
}
