// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function handleRemoteFetch(this: CommandController, arg?: unknown): Promise<void> {
  const remoteName = this.asBranchRemoteItem(arg)?.remoteName;
  if (!remoteName) {
    return;
  }

  await this.git.runGit(['fetch', remoteName]);
  await this.state.refreshAll();
  void vscode.window.showInformationMessage(`Fetched remote ${remoteName}.`);
}
