// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';
import { GitCommand } from '../../config/commands';
import { GraphCommitTreeItem } from '../../providers/graphTreeProvider';

export async function handleGraphGoToParentCommit(this: CommandController, arg?: unknown): Promise<void> {
  const sha = this.toCommitSha(arg) ?? (await this.pickCommitSha('Pick commit'));
      if (!sha) {
        return;
      }
  
      const parent = await this.git.getParentCommit(sha);
      if (!parent) {
        void vscode.window.showInformationMessage('This commit has no parent commit.');
        return;
      }
  
      const graphCommit = this.state.graph.find((commit) => commit.sha === parent);
      if (graphCommit) {
        await vscode.commands.executeCommand(
          GitCommand.GraphOpenDetails,
          new GraphCommitTreeItem(graphCommit)
        );
      } else {
        const subject = (await this.git.getCommitDetails(parent)).commit.subject;
        await this.openCommitDetails(parent, subject, { openFirstDiff: true });
      }
}
