// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function handleWorktreeAddNewBranch(this: CommandController): Promise<void> {
  const branchName = await vscode.window.showInputBox({
        title: 'New branch name',
        placeHolder: 'feature/my-branch',
        validateInput: (v) => (v.trim() ? undefined : 'Branch name is required')
      });
      if (!branchName) {
        return;
      }
  
      const base = await this.pickWorktreeRevision('Select base branch, tag, or revision');
  
      const targetPath = await this.pickWorktreeTargetPath(
        'Select Worktree Folder',
        branchName.trim()
      );
      if (!targetPath) {
        return;
      }
  
      await this.git.addWorktreeBranch(targetPath, branchName.trim(), base?.ref);
      await this.state.refreshWorktrees();
}
