// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function handleWorktreePrune(this: CommandController): Promise<void> {
  const prunable = await this.git.getPrunableWorktrees();
      if (prunable.length === 0) {
        void vscode.window.showInformationMessage('No prunable worktrees found.');
        return;
      }
  
      const items = prunable.map((p) => ({ label: p.worktreePath, description: p.reason }));
      const confirmed = await vscode.window.showQuickPick(items, {
        title: `Prune ${prunable.length} stale worktree(s)?`,
        placeHolder: 'Review — confirm by pressing Enter',
        canPickMany: false
      });
      if (!confirmed) {
        return;
      }
  
      await this.git.pruneWorktrees();
      await this.state.refreshWorktrees();
      void vscode.window.showInformationMessage('Stale worktrees pruned.');
}
