// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';
import { GitCommand } from '../../config/commands';
import { confirmDangerousAction } from '../../guards';

export async function handlePushAllUpToHere(this: CommandController, arg?: unknown): Promise<void> {
  const sha = this.toCommitSha(arg) ?? (await this.pickCommitSha('Pick commit to push up to'));
      if (!sha) {
        return;
      }
  
      const current = (await this.git.runGit(['rev-parse', 'HEAD'])).stdout.trim();
      if (current === sha) {
        await vscode.commands.executeCommand(GitCommand.GitPushWithPreview);
        return;
      }
  
      let isAncestor = true;
      try {
        await this.git.runGit(['merge-base', '--is-ancestor', sha, 'HEAD']);
      } catch {
        isAncestor = false;
      }
      if (!isAncestor) {
        void vscode.window.showWarningMessage('Selected commit is not an ancestor of current HEAD.');
        return;
      }
  
      const preview = await this.git.runGit(['log', '--oneline', `${sha}..HEAD`]);
      const outgoingLines = preview.stdout
        .split('\n')
        .map((line) => line.trim())
        .filter(Boolean);
      const detailLines = outgoingLines.slice(0, 10).join('\n') || 'none';
  
      const confirmed = await confirmDangerousAction({
        title: `Push all up to ${sha.slice(0, 8)}`,
        detail: `Commits to push:\n${detailLines}`,
        acceptLabel: 'Push'
      });
      if (!confirmed) {
        return;
      }
  
      await this.git.push();
      await this.state.refreshAll();
}
