// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { BranchSearchView } from '../../views/branchSearchView';

export async function handleBranchSearchRefresh(this: CommandController): Promise<void> {
  await BranchSearchView.refreshCurrent();
}
