// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function handleTagCreatePatch(this: CommandController, arg?: unknown): Promise<void> {
  const revision =
        this.toTagRevision(arg) ?? (await this.pickCommitSha('Pick revision to export patch'));
      if (!revision) {
        return;
      }
      const patch = await this.git.getPatchForCommit(revision);
      const doc = await vscode.workspace.openTextDocument({ language: 'diff', content: patch });
      await vscode.window.showTextDocument(doc, { preview: false });
}
