// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { confirmDangerousAction } from '../../guards';
import { SubmoduleTreeItem } from '../../providers/submoduleTreeProvider';
import { withSubmoduleProgress } from '../helpers/with-submodule-progress';

export async function handleSubmoduleUpdate(this: CommandController, arg?: unknown): Promise<void> {
  const item = arg instanceof SubmoduleTreeItem ? arg : undefined;
      if (!item) {
        return;
      }
  
      if (item.submodule.isDirty) {
        const confirmed = await confirmDangerousAction({
          title: 'Update dirty submodule',
          detail: `${item.submodule.path} has uncommitted changes.`,
          acceptLabel: 'Update anyway'
        });
        if (!confirmed) {
          return;
        }
      }
  
      try {
        await withSubmoduleProgress(
          this.logger,
          {
            title: `Updating submodule ${item.submodule.path}…`,
            autoShow: false,
            command: 'Submodule update'
          },
          ({ sink, signal }) => this.git.updateSubmodule(item.submodule.path, false, { sink, signal })
        );
      } finally {
        await this.state.refreshSubmodules();
      }
}
