// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { confirmDangerousAction } from '../../guards';

export async function handleGraphCherryPickRange(this: CommandController): Promise<void> {
  const fromExclusive = await this.pickCommitSha('Pick starting point (exclusive)');
      if (!fromExclusive) {
        return;
      }
      const toInclusive = await this.pickCommitSha('Pick end point (inclusive)');
      if (!toInclusive) {
        return;
      }
  
      const confirmed = await confirmDangerousAction({
        title: 'Cherry-pick range',
        detail: `${fromExclusive}..${toInclusive}`,
        acceptLabel: 'Cherry-pick'
      });
      if (!confirmed) {
        return;
      }
  
      await this.git.cherryPickRange(fromExclusive, toInclusive);
      await this.state.refreshAll();
}
