// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function handleOperationConflict(this: CommandController, operation: 'cherry-pick' | 'merge' | 'rebase', refreshPromise: Promise<void>): Promise<void> {
  void vscode.window.showWarningMessage(
        'There are some conflicts. You have to resolve them first.'
      );
      await refreshPromise;
      await this.openOperationConflictEditors(operation);
}
