// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleTagCompareWithCurrent(this: CommandController, arg?: unknown): Promise<void> {
  const revision =
        this.toTagRevision(arg) ??
        (await this.pickCommitSha('Pick revision to compare with current'));
      if (!revision) {
        return;
      }
      await this.editor.openCompareFromCommit(revision);
}
