// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleGraphOpenRepositoryFileAtRevision(this: CommandController, arg?: unknown): Promise<void> {
  const item = this.asRevisionViewFileItem(arg);
      if (!item) {
        return;
      }
  
      await this.editor.openFileAtRevision(item.sha, item.filePath);
}
