// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleConflictAcceptTheirs(this: CommandController, arg?: unknown): Promise<void> {
  await this.handleConflictResolve(arg, 'theirs');
}
