// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { confirmDangerousAction } from '../../guards';

export async function handleBranchRebaseOnto(this: CommandController, arg?: unknown): Promise<void> {
  const onto =
        this.toBranchName(arg) ?? (await this.pickBranchName('Pick branch to rebase onto'));
      if (!onto) {
        return;
      }
  
      const confirmed = await confirmDangerousAction({
        title: 'Rebase current branch',
        detail: `Rebase onto: ${onto}`,
        acceptLabel: 'Rebase'
      });
      if (!confirmed) {
        return;
      }
  
      await this.startRebaseOperation(() => this.git.rebaseCurrentOnto(onto));
}
