// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleCompareWithRevisionSwapDirection(this: CommandController): Promise<void> {
  await this.editor.swapActiveCompareDirection();
}
