// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleBranchUntrack(this: CommandController, arg?: unknown): Promise<void> {
  const branch =
        this.toBranchName(arg) ?? (await this.pickBranchName('Pick local branch to untrack'));
      if (!branch) {
        return;
      }
  
      await this.git.untrackBranch(branch);
      await this.state.refreshAll();
}
