// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { openCompareWorkflow } from './openCompareWorkflow';

export async function handleCompareOpen(this: CommandController): Promise<void> {
  await this.openCompareWorkflow();
}
