// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function handleTagCheckoutNewBranch(this: CommandController, arg?: unknown): Promise<void> {
  const baseRef =
        this.toTagRef(arg) ?? (await this.pickCommitSha('Pick tag or revision for new branch'));
      if (!baseRef) {
        return;
      }
  
      const branchName = await vscode.window.showInputBox({
        title: `Checkout new branch from ${baseRef}`,
        placeHolder: 'feature/new-branch',
        validateInput: (value) => (value.trim() ? undefined : 'Branch name is required')
      });
  
      if (!branchName) {
        return;
      }
  
      await this.git.createBranch(branchName.trim(), baseRef);
      await this.git.checkoutBranch(branchName.trim());
      await this.state.refreshAll();
}
