// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function handleStageFile(this: CommandController): Promise<void> {
  const changed = await this.git.getChangedFiles();
      const candidates = changed.filter(
        (entry) => entry.status.length > 0 && entry.status[1] !== ' '
      );
      if (candidates.length === 0) {
        void vscode.window.showInformationMessage('No unstaged files found.');
        return;
      }
  
      const file = await vscode.window.showQuickPick(
        candidates.map((item) => ({ label: item.path, description: item.status })),
        { title: 'Stage file' }
      );
      if (!file) {
        return;
      }
  
      await this.git.stageFile(file.label);
      await this.state.refreshAll();
}
