// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleBranchCompareWithCurrent(this: CommandController, arg?: unknown): Promise<void> {
  const current = await this.git.getCurrentBranch();
      const target =
        this.toBranchName(arg) ?? (await this.pickBranchName('Pick branch to compare with current'));
      if (!target) {
        return;
      }
  
      await this.editor.openBranchCompare(current, target);
}
