// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';
import { WorktreeTreeItem } from '../../providers/worktreeTreeProvider';

export async function handleWorktreeOpenTerminal(this: CommandController, arg?: unknown): Promise<void> {
  const item = arg instanceof WorktreeTreeItem ? arg : undefined;
      if (!item) {
        return;
      }
      const terminal = vscode.window.createTerminal({
        cwd: item.worktree.worktreePath,
        name: `Worktree: ${item.label}`
      });
      terminal.show();
}
