// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';
import { SubmoduleTreeItem } from '../../providers/submoduleTreeProvider';

export async function handleSubmoduleOpen(this: CommandController, arg?: unknown): Promise<void> {
  const item = arg instanceof SubmoduleTreeItem ? arg : undefined;
      if (!item) {
        return;
      }
      const fullPath = `${this.git.gitRoot}/${item.submodule.path}`;
      await vscode.commands.executeCommand('vscode.openFolder', vscode.Uri.file(fullPath), {
        forceReuseWindow: true
      });
}
