// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleGraphOpenDetails(this: CommandController, arg?: unknown, selected?: unknown): Promise<void> {
  const selectedShas = this.toGraphCommitShas(arg, selected);
      const shouldOpenFirstDiff =
        this.asGraphItem(arg) !== undefined ||
        (Array.isArray(selected) && selected.some((item) => this.asGraphItem(item) !== undefined));
      if (selectedShas.length === 0) {
        const picked = await this.pickCommitSha('Pick commit for details');
        if (!picked) {
          return;
        }
        selectedShas.push(picked);
      }
      const sha = selectedShas[0];
      if (!sha) {
        return;
      }
      const subject = this.resolveCommitSubject(sha, arg, selected);
      await this.openCommitDetails(sha, subject, {
        openFirstDiff: shouldOpenFirstDiff,
        allowToggle: true
      });
}
