// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleGitSshPullCustom(this: CommandController): Promise<void> {
  await this.sshPull('prompt');
}
