// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleWorkingTreeCompareOpenFileDiff(this: CommandController, arg?: unknown): Promise<void> {
  const item = this.asWorkingTreeCompareFileItem(arg);
      if (!item) {
        return;
      }
  
      await this.editor.openWorkingTreeFileDiff(item.filePath, item.ref, item.refLabel, {
        preview: true,
        status: item.status
      });
}
