// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function handleUnstageFile(this: CommandController): Promise<void> {
  const changed = await this.git.getChangedFiles();
      const candidates = changed.filter(
        (entry) => entry.status.length > 1 && entry.status[0] !== ' ' && entry.status[0] !== '?'
      );
      if (candidates.length === 0) {
        void vscode.window.showInformationMessage('No staged files found.');
        return;
      }
  
      const file = await vscode.window.showQuickPick(
        candidates.map((item) => ({ label: item.path, description: item.status })),
        { title: 'Unstage file' }
      );
      if (!file) {
        return;
      }
  
      await this.git.unstageFile(file.label);
      await this.state.refreshAll();
}
