// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleWorktreeAddFromBranch(this: CommandController): Promise<void> {
  const selection = await this.pickWorktreeRevision('Add worktree from branch, tag, or revision');
      if (!selection) {
        return;
      }
  
      const targetPath = await this.pickWorktreeTargetPath('Select Worktree Folder', selection.ref);
      if (!targetPath) {
        return;
      }
  
      await this.git.addWorktree(targetPath, selection.ref);
      await this.state.refreshWorktrees();
}
