// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleGraphRevert(this: CommandController, arg?: unknown, selected?: unknown): Promise<void> {
  const selectedShas = this.toGraphCommitShas(arg, selected);
      if (selectedShas.length === 0) {
        const picked = await this.pickCommitSha('Pick commit to revert');
        if (!picked) {
          return;
        }
        selectedShas.push(picked);
      }
  
      for (const sha of selectedShas) {
        await this.git.revertCommit(sha);
      }
      await this.state.refreshAll();
}
