// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function handleGraphCreateBranchHere(this: CommandController, arg?: unknown): Promise<void> {
  const sha = this.toCommitSha(arg) ?? (await this.pickCommitSha('Pick commit for new branch'));
      if (!sha) {
        return;
      }
  
      const name = await vscode.window.showInputBox({
        title: `Create branch at ${sha.slice(0, 8)}`,
        placeHolder: 'feature/new-branch',
        validateInput: (value) => (value.trim() ? undefined : 'Branch name is required')
      });
  
      if (!name) {
        return;
      }
  
      await this.git.createBranch(name.trim(), sha);
      await this.state.refreshAll();
}
