// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';
import { GitCommand } from '../../config/commands';
import { getConfigValue } from '../../configuration';
import { GraphFilterSession } from '../../views/graphFilterSession';
import { GraphFilterView } from '../../views/graphFilterView';

export async function handleGraphFilter(this: CommandController): Promise<void> {
  const filterSession = new GraphFilterSession(
        (maxCount, skip, filters) => this.git.getGraph(maxCount, skip, filters),
        () => getConfigValue<number>('maxGraphCommits', 200)
      );
      const getMasterSnapshot = () => ({
        filters: {},
        branches: this.state.branches,
        commits: this.state.graph,
        hasMore: this.state.graphHasMore
      });
      GraphFilterView.open(
        {
          apply: async (filters) => {
            const snapshot = await filterSession.apply(filters);
            const isActive = Object.values(filters).some(Boolean);
            await vscode.commands.executeCommand(
              'setContext',
              GitCommand.GraphFilterActive,
              isActive
            );
            return snapshot;
          },
          clear: async () => {
            await vscode.commands.executeCommand('setContext', GitCommand.GraphFilterActive, false);
            return filterSession.clear(getMasterSnapshot());
          },
          openCommitDetails: async (sha, subject) =>
            this.openCommitDetails(sha, subject, { allowToggle: true }),
          openCommitRangeDetails: async (shas) => this.editor.openCommitRangeDetails(shas),
          getCommitFiles: async (sha) => this.git.getFilesInCommit(sha),
          openFileDiff: async (sha, filePath) => this.editor.openCommitFileDiff(sha, filePath),
          loadMore: async () => {
            return filterSession.loadMore(getMasterSnapshot());
          }
        },
        () => ({
          ...filterSession.getSnapshot(getMasterSnapshot()),
          branches: this.state.branches
        })
      );
}
