// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function handleStagePatch(this: CommandController): Promise<void> {
  const changed = await this.git.getChangedFiles();
      if (changed.length === 0) {
        void vscode.window.showInformationMessage('No local changes found.');
        return;
      }
  
      const file = await vscode.window.showQuickPick(
        changed.map((item) => ({ label: item.path, description: item.status })),
        { title: 'Select file for interactive hunk staging' }
      );
  
      if (!file) {
        return;
      }
  
      await this.git.stagePatch(file.label);
      await this.state.refreshAll();
}
