// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';
import { WorktreeTreeItem } from '../../providers/worktreeTreeProvider';

export async function handleWorktreeOpen(this: CommandController, arg?: unknown): Promise<void> {
  const item = arg instanceof WorktreeTreeItem ? arg : undefined;
      const worktreePath = item?.worktree.worktreePath;
      if (!worktreePath) {
        return;
      }
      await vscode.commands.executeCommand('vscode.openFolder', vscode.Uri.file(worktreePath), {
        forceReuseWindow: true
      });
}
