// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { openBranchActionHub } from './openBranchActionHub';

export async function handleBranchActionHub(this: CommandController, arg?: unknown): Promise<void> {
  await this.openBranchActionHub(arg);
}
