// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { confirmDangerousAction } from '../../guards';
import { SubmoduleTreeItem } from '../../providers/submoduleTreeProvider';
import { withSubmoduleProgress } from '../helpers/with-submodule-progress';

export async function handleSubmoduleDeinit(this: CommandController, arg?: unknown): Promise<void> {
  const item = arg instanceof SubmoduleTreeItem ? arg : undefined;
      if (!item) {
        return;
      }
  
      if (item.submodule.isDirty) {
        const confirmed = await confirmDangerousAction({
          title: 'Deinit dirty submodule',
          detail: `${item.submodule.path} has uncommitted changes that will be lost.`,
          acceptLabel: 'Deinit'
        });
        if (!confirmed) {
          return;
        }
      } else {
        const confirmed = await confirmDangerousAction({
          title: 'Deinit submodule',
          detail: `This will remove ${item.submodule.path} from the working tree.`,
          acceptLabel: 'Deinit'
        });
        if (!confirmed) {
          return;
        }
      }
  
      try {
        await withSubmoduleProgress(
          this.logger,
          {
            title: `Deiniting submodule ${item.submodule.path}…`,
            autoShow: false,
            command: 'Submodule deinit'
          },
          ({ sink, signal }) =>
            this.git.deinitSubmodule(item.submodule.path, item.submodule.isDirty, { sink, signal })
        );
      } finally {
        await this.state.refreshSubmodules();
      }
}
