// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleStashPop(this: CommandController, arg?: unknown): Promise<void> {
  await this.handleStashApplyPop(arg, true);
}
