// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleGraphCompareWithCurrent(this: CommandController, arg?: unknown): Promise<void> {
  const sha =
        this.toCommitSha(arg) ?? (await this.pickCommitSha('Pick commit to compare with current'));
      if (!sha) {
        return;
      }
  
      await this.editor.openCompareFromCommit(sha);
}
