// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function handleRemoteFetchAll(this: CommandController): Promise<void> {
  await this.git.runGit(['fetch', '--all']);
  await this.state.refreshAll();
  void vscode.window.showInformationMessage('Fetched all remotes.');
}
