// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function handleApplyPatch(this: CommandController): Promise<void> {
  const source = await this.pickPatchSource();
      if (!source) {
        return;
      }
  
      const patch =
        source.kind === 'clipboard'
          ? await vscode.env.clipboard.readText()
          : await this.readPatchFromFile();
      if (patch === undefined) {
        return;
      }
  
      if (!patch.trim()) {
        void vscode.window.showWarningMessage('Patch content is empty.');
        return;
      }
  
      await this.applyPatchToWorkingTree(patch, {
        source: source.kind === 'clipboard' ? 'clipboard' : 'patch file'
      });
}
