// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { confirmDangerousAction } from '../../guards';

export async function handleTagCheckout(this: CommandController, arg?: unknown): Promise<void> {
  const tagRef =
        this.toTagRef(arg) ?? (await this.pickCommitSha('Pick tag or revision to checkout'));
      if (!tagRef) {
        return;
      }
  
      const confirmed = await confirmDangerousAction({
        title: 'Checkout revision',
        detail: `Revision: ${tagRef}`,
        acceptLabel: 'Checkout'
      });
      if (!confirmed) {
        return;
      }
  
      await this.git.checkoutCommit(tagRef);
      await this.state.refreshAll();
}
