// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { confirmDangerousAction } from '../../guards';

export async function handleGraphCheckoutCommit(this: CommandController, arg?: unknown): Promise<void> {
  const sha = this.toCommitSha(arg) ?? (await this.pickCommitSha('Pick commit to checkout'));
      if (!sha) {
        return;
      }
  
      const confirmed = await confirmDangerousAction({
        title: 'Checkout detached HEAD',
        detail: `Commit: ${sha}`,
        acceptLabel: 'Checkout'
      });
      if (!confirmed) {
        return;
      }
  
      await this.git.checkoutCommit(sha);
      await this.state.refreshAll();
}
