// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleBranchCheckout(this: CommandController, arg?: unknown): Promise<void> {
  const branchName = this.toBranchName(arg) ?? (await this.pickBranchName());
      if (!branchName) {
        return;
      }
  
      await this.git.checkoutBranch(branchName);
      await this.state.refreshAll();
}
