// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function handleWorktreePrunePreview(this: CommandController): Promise<void> {
  const prunable = await this.git.getPrunableWorktrees();
      if (prunable.length === 0) {
        void vscode.window.showInformationMessage('No prunable worktrees found.');
        return;
      }
  
      const items = prunable.map((p) => ({ label: p.worktreePath, description: p.reason }));
      await vscode.window.showQuickPick(items, {
        title: 'Prunable worktrees (dry run)',
        placeHolder: 'These worktrees would be pruned',
        canPickMany: false
      });
}
