// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';
import { getConfigValue } from '../../configuration';

export async function handleGenerateCommitMessage(this: CommandController): Promise<void> {
  const repository = await this.getBuiltInGitRepository();
      if (!repository) {
        void vscode.window.showWarningMessage('Git repository context not available.');
        return;
      }
  
      const timeoutMs = getConfigValue<number>('aiGenerateTimeoutMs', 5000);
      const cts = new vscode.CancellationTokenSource();
      const timer = setTimeout(() => cts.cancel(), timeoutMs);
  
      try {
        const generated = await this.git.generateCommitMessage(cts.token);
        repository.inputBox.value = generated;
      } catch (error) {
        const message = cts.token.isCancellationRequested
          ? `AI generation timed out after ${timeoutMs / 1000}s.`
          : String(error);
        void vscode.window.showErrorMessage(message);
      } finally {
        clearTimeout(timer);
        cts.dispose();
      }
}
