// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { withSubmoduleProgress } from '../helpers/with-submodule-progress';

export async function handleSubmoduleInitAll(this: CommandController): Promise<void> {
  const count = this.state.submodules.length;
      try {
        await withSubmoduleProgress(
          this.logger,
          {
            title: `Initializing ${count} submodule(s)…`,
            autoShow: true,
            command: 'Submodule init (all)'
          },
          ({ sink, signal }) => this.git.initAllSubmodules({ sink, signal })
        );
      } finally {
        await this.state.refreshSubmodules();
      }
}
