// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';
import { GitCommand } from '../../config/commands';
import { BranchSearchView } from '../../views/branchSearchView';

export async function handleBranchSearch(this: CommandController): Promise<void> {
  const searchView = BranchSearchView.open(
        {
          checkout: async (name: string) => {
            await this.git.checkoutBranch(name);
            await this.state.refreshAll();
          },
          checkoutTag: async (name: string) => {
            await vscode.commands.executeCommand(GitCommand.TagCheckoutNewBranch, name);
            await this.state.refreshAll();
          },
          openActions: async (name: string) => {
            await vscode.commands.executeCommand(GitCommand.BranchActionHub, name);
          },
          refresh: async () => {
            await this.state.refreshBranches();
          },
          runCommand: async (command, name) => {
            await vscode.commands.executeCommand(command, name);
          }
        },
        () => this.state.branches,
        () => this.state.tags,
        (listener) => this.state.onDidChange(listener)
      );
      await searchView.refresh();
}
