// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { confirmDangerousAction } from '../../guards';

export async function handleBranchDelete(this: CommandController, arg?: unknown): Promise<void> {
  const branch = this.toBranchName(arg) ?? (await this.pickBranchName('Pick branch to delete'));
      if (!branch) {
        return;
      }
  
      const confirmed = await confirmDangerousAction({
        title: 'Delete branch',
        detail: `Branch: ${branch}`,
        acceptLabel: 'Delete'
      });
      if (!confirmed) {
        return;
      }
  
      await this.git.deleteBranch(branch);
      await this.state.refreshAll();
}
