// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function handleRemoteAdd(this: CommandController): Promise<void> {
  const remoteUrl = await vscode.window.showInputBox({
        title: 'Add Git remote',
        placeHolder: 'https://github.com/org/repo.git',
        validateInput: (value) => (value.trim() ? undefined : 'Remote URL is required')
      });
      if (!remoteUrl) {
        return;
      }
  
      const remoteName = await vscode.window.showInputBox({
        title: 'Remote name',
        placeHolder: 'origin',
        validateInput: (value) => (value.trim() ? undefined : 'Remote name is required')
      });
      if (!remoteName) {
        return;
      }
  
      await this.git.addRemote(remoteName.trim(), remoteUrl.trim());
      await this.state.refreshBranches();
      void vscode.window.showInformationMessage(`Added remote ${remoteName.trim()}.`);
}
