// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleConflictAcceptOurs(this: CommandController, arg?: unknown): Promise<void> {
  await this.handleConflictResolve(arg, 'ours');
}
