// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function handleBranchRename(this: CommandController, arg?: unknown): Promise<void> {
  const from = this.toBranchName(arg) ?? (await this.pickBranchName('Pick branch to rename'));
      if (!from) {
        return;
      }
  
      const to = await vscode.window.showInputBox({
        title: `Rename branch ${from}`,
        value: from,
        validateInput: (value) => (value.trim() ? undefined : 'Branch name is required')
      });
  
      if (!to || to.trim() === from) {
        return;
      }
  
      await this.git.renameBranch(from, to.trim());
      await this.state.refreshAll();
}
