// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';
import { pickRevisionToCompare } from '../../views/revisionPicker';

export async function handleCompareWithRevision(this: CommandController, arg?: unknown, selected?: unknown): Promise<void> {
  const targetUris = this.toExplorerResourceUris(arg, selected);
      if (targetUris.length === 0) {
        void vscode.window.showWarningMessage(
          'Right-click a file or folder in the Explorer to compare.'
        );
        return;
      }
  
      if (!(await this.git.isRepo())) {
        void vscode.window.showErrorMessage('Not inside a Git repository');
        return;
      }
  
      const gitRoot = await this.git.getGitRoot();
      const normalizedRoot = gitRoot.replace(/[\\/]+$/, '');
      const targets: Array<{ repoRelative: string; isDirectory: boolean }> = [];
      for (const uri of targetUris) {
        const normalizedTarget = uri.fsPath.replace(/[\\/]+$/, '');
        const repoRelative =
          normalizedTarget === normalizedRoot ? '' : this.git.toRepoRelative(uri.fsPath);
        if (repoRelative === undefined) {
          void vscode.window.showErrorMessage('Not inside a Git repository');
          return;
        }
  
        let stat: vscode.FileStat;
        try {
          stat = await vscode.workspace.fs.stat(uri);
        } catch {
          void vscode.window.showErrorMessage('Selected path is no longer available.');
          return;
        }
        targets.push({
          repoRelative,
          isDirectory: (stat.type & vscode.FileType.Directory) !== 0
        });
      }
  
      const selection = await pickRevisionToCompare(
        this.git,
        () => this.state.branches,
        () => this.state.tags,
        () => this.state.refreshBranches()
      );
      if (!selection) {
        return;
      }
  
      for (const target of targets) {
        if (target.isDirectory) {
          await this.editor.openCompareWithRevisionForFolder(
            target.repoRelative,
            selection.ref,
            selection.label
          );
        } else {
          await this.editor.openCompareWithRevisionForFile(
            target.repoRelative,
            selection.ref,
            selection.label
          );
        }
      }
}
