// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { confirmDangerousAction } from '../../guards';
import { withSubmoduleProgress } from '../helpers/with-submodule-progress';

export async function handleSubmoduleUpdateRecursive(this: CommandController): Promise<void> {
  const submodules = this.state.submodules;
      const dirtyCount = submodules.filter((s) => s.isDirty).length;
      const confirmed = await confirmDangerousAction({
        title: 'Update all submodules recursively',
        detail:
          dirtyCount > 0
            ? `${submodules.length} submodule(s) will be updated recursively. ${dirtyCount} have uncommitted changes.`
            : `${submodules.length} submodule(s) will be updated recursively.`,
        acceptLabel: 'Update Recursive'
      });
      if (!confirmed) {
        return;
      }
      try {
        await withSubmoduleProgress(
          this.logger,
          {
            title: `Recursively updating ${submodules.length} submodule(s)…`,
            autoShow: true,
            command: 'Submodule update (recursive)'
          },
          ({ sink, signal }) => this.git.updateAllSubmodules(true, { sink, signal })
        );
      } finally {
        await this.state.refreshSubmodules();
      }
}
