// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { SubmoduleTreeItem } from '../../providers/submoduleTreeProvider';

export async function handleSubmoduleStagePointerChange(this: CommandController, arg?: unknown): Promise<void> {
  const item = arg instanceof SubmoduleTreeItem ? arg : undefined;
      if (!item) {
        return;
      }
      await this.git.stageSubmodulePointer(item.submodule.path);
      await this.state.refreshAll();
}
