// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function handleCreatePatchSelectedChanges(this: CommandController, arg?: unknown, selected?: unknown): Promise<void> {
  const target = await this.resolveSelectedCommitFiles(arg, selected);
      if (!target) {
        void vscode.window.showInformationMessage('Select one or more files from a commit first.');
        return;
      }
  
      if (!target.canCreatePatch) {
        void vscode.window.showWarningMessage(
          'Selected files cannot be used to create a patch from this view.'
        );
        return;
      }
  
      const patch =
        target.kind === 'commit'
          ? await this.git.getPatchForCommitFiles(target.sha, target.filePaths)
          : target.kind === 'range'
            ? await this.git.getPatchBetweenRefsForFiles(
                target.fromRef,
                target.toRef,
                target.filePaths
              )
            : await this.git.getPatchBetweenWorkingTreeAndRefForFiles(target.ref, target.filePaths);
      if (!patch.trim()) {
        void vscode.window.showInformationMessage(
          'No patch content generated for the selected files.'
        );
        return;
      }
  
      const output = await this.pickPatchOutputTarget('Create Patch');
      if (!output) {
        return;
      }
  
      const patchFileName = '@unnamed.patch';
      if (output === 'clipboard') {
        await vscode.env.clipboard.writeText(patch);
      } else {
        const workspaceRoot = vscode.workspace.workspaceFolders?.[0]?.uri;
        const defaultUri = workspaceRoot
          ? vscode.Uri.joinPath(workspaceRoot, patchFileName)
          : undefined;
        const targetUri = await vscode.window.showSaveDialog({
          title: 'Save Patch File',
          saveLabel: 'Save',
          defaultUri,
          filters: {
            Patch: ['patch', 'diff']
          }
        });
        if (!targetUri) {
          return;
        }
        await vscode.workspace.fs.writeFile(targetUri, Buffer.from(patch, 'utf8'));
      }
  
      if (target.kind !== 'workingTreeCompare') {
        await this.applyPatchToWorkingTree(patch, {
          source: `selected changes from ${target.shortLabel}`
        });
      }
}
