// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { WorktreeTreeItem } from '../../providers/worktreeTreeProvider';

export async function handleWorktreeUnlock(this: CommandController, arg?: unknown): Promise<void> {
  const item = arg instanceof WorktreeTreeItem ? arg : undefined;
      if (!item) {
        return;
      }
  
      await this.git.unlockWorktree(item.worktree.worktreePath);
      await this.state.refreshWorktrees();
}
