// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleSubmoduleRefresh(this: CommandController): Promise<void> {
  await this.state.refreshSubmodules();
}
