// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';
import { GitCommand } from '../../config/commands';

export async function handleOperationContinue(this: CommandController): Promise<void> {
  const state = await this.git.getOperationState();
      if (state.kind === 'none') {
        void vscode.window.showInformationMessage('No merge/rebase/cherry-pick/revert in progress.');
        return;
      }
      const conflicts = await this.git.getMergeConflicts();
      if (conflicts.length > 0) {
        if (state.kind === 'rebase') {
          await this.handleRebaseConflict();
          return;
        }
        void vscode.window.showWarningMessage(
          `Resolve all conflicts before continuing (${conflicts.length} remaining).`
        );
        return;
      }
      try {
        if (state.kind === 'merge') {
          await vscode.commands.executeCommand(GitCommand.MergeFinalize);
          return;
        }
        if (state.kind === 'rebase') {
          try {
            await this.git.rebaseContinue();
          } catch (error) {
            const issue = this.classifyRebaseIssue(error);
            if (issue.kind === 'conflict') {
              await this.handleOperationConflict('rebase', this.state.refreshAll());
              return;
            }
            throw error;
          }
          await this.state.refreshAll();
          await this.showRebaseProgressFeedback();
          return;
        }
        if (state.kind === 'cherry-pick') {
          await this.git.cherryPickContinue();
        } else if (state.kind === 'revert') {
          await this.git.revertContinue();
        }
      } finally {
        if (state.kind !== 'rebase') {
          await this.state.refreshAll();
        }
      }
}
