// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { confirmDangerousAction } from '../../guards';

export async function handleWorktreeAddDetached(this: CommandController): Promise<void> {
  const selection = await this.pickWorktreeRevision(
        'Detached worktree at branch, tag, or revision'
      );
      if (!selection) {
        return;
      }
  
      const targetPath = await this.pickWorktreeTargetPath('Select Worktree Folder', selection.ref);
      if (!targetPath) {
        return;
      }
  
      const confirmed = await confirmDangerousAction({
        title: 'Add detached worktree',
        detail: `This creates a worktree in detached HEAD state at ${selection.ref}`,
        acceptLabel: 'Create Detached'
      });
      if (!confirmed) {
        return;
      }
  
      await this.git.addDetachedWorktree(targetPath, selection.ref);
      await this.state.refreshWorktrees();
}
