// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { confirmDangerousAction } from '../../guards';
import { withSubmoduleProgress } from '../helpers/with-submodule-progress';

export async function handleSubmoduleUpdateAll(this: CommandController): Promise<void> {
  const submodules = this.state.submodules;
      const dirtyCount = submodules.filter((s) => s.isDirty).length;
      if (dirtyCount > 0) {
        const confirmed = await confirmDangerousAction({
          title: 'Update all submodules',
          detail: `${dirtyCount} submodule(s) have uncommitted changes.`,
          acceptLabel: 'Update all'
        });
        if (!confirmed) {
          return;
        }
      }
      try {
        await withSubmoduleProgress(
          this.logger,
          {
            title: `Updating ${submodules.length} submodule(s)…`,
            autoShow: true,
            command: 'Submodule update (all)'
          },
          ({ sink, signal }) => this.git.updateAllSubmodules(false, { sink, signal })
        );
      } finally {
        await this.state.refreshSubmodules();
      }
}
