// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleGitSshPullGithub(this: CommandController): Promise<void> {
  await this.sshPull('github.com');
}
