// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';
import { confirmDangerousAction } from '../../guards';
import { WorktreeTreeItem } from '../../providers/worktreeTreeProvider';

export async function handleWorktreeRemoveForce(this: CommandController, arg?: unknown): Promise<void> {
  const item = arg instanceof WorktreeTreeItem ? arg : undefined;
      if (!item) {
        return;
      }
      const { worktree } = item;
  
      if (worktree.isCurrent) {
        void vscode.window.showWarningMessage('Cannot remove the current worktree.');
        return;
      }
  
      const confirmed = await confirmDangerousAction({
        title: 'Force remove worktree',
        detail: `${worktree.worktreePath} — all local changes will be lost. This cannot be undone.`,
        acceptLabel: 'Force Remove'
      });
      if (!confirmed) {
        return;
      }
  
      await this.git.removeWorktree(worktree.worktreePath, true);
      await this.state.refreshWorktrees();
}
