// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function handleCherryPick(this: CommandController, arg?: unknown, selected?: unknown): Promise<void> {
  const selectedShas = this.toGraphCommitShas(arg, selected);
      if (selectedShas.length === 0) {
        const picked = await this.pickCommitSha('Pick commit to cherry-pick');
        if (!picked) {
          return;
        }
        selectedShas.push(picked);
      }
  
      const orderedShas = await this.orderShasForCherryPick(selectedShas);
  
      const pickedShas: string[] = [];
      const emptyShas: string[] = [];
      const failedShas: string[] = [];
      let conflictSha: string | undefined;
      let issueMessage: string | undefined;
  
      for (const sha of orderedShas) {
        try {
          await this.git.cherryPick(sha);
          pickedShas.push(sha);
        } catch (error) {
          const issue = this.classifyCherryPickIssue(error);
          issueMessage = issue.message;
          if (issue.kind === 'nothingToCherryPick') {
            emptyShas.push(sha);
            continue;
          }
          if (issue.kind === 'conflict') {
            conflictSha = sha;
            break;
          }
          failedShas.push(sha);
          break;
        }
      }
  
      const refreshPromise = this.state.refreshAll();
  
      if (conflictSha) {
        await this.handleOperationConflict('cherry-pick', refreshPromise);
        return;
      }
  
      if (failedShas.length > 0) {
        const detail = issueMessage ? ` ${issueMessage}` : '';
        const prefix =
          pickedShas.length > 0
            ? `Cherry-pick stopped after applying ${pickedShas.length} commit(s).`
            : 'Cherry-pick failed.';
        void vscode.window.showErrorMessage(`${prefix}${detail}`);
        await refreshPromise;
        return;
      }
  
      if (pickedShas.length > 0 && emptyShas.length === 0) {
        const message =
          pickedShas.length === 1
            ? `Cherry-pick succeeded for ${pickedShas[0].slice(0, 8)}.`
            : `Cherry-pick succeeded for ${pickedShas.length} commit(s).`;
        void vscode.window.showInformationMessage(message);
        await refreshPromise;
        return;
      }
  
      if (pickedShas.length === 0 && emptyShas.length > 0) {
        const message =
          emptyShas.length === 1
            ? `Nothing to cherry-pick for ${emptyShas[0].slice(0, 8)} (already applied or empty).`
            : `Nothing to cherry-pick for ${emptyShas.length} commit(s) (already applied or empty).`;
        void vscode.window.showInformationMessage(message);
        await refreshPromise;
        return;
      }
  
      if (pickedShas.length > 0 && emptyShas.length > 0) {
        void vscode.window.showInformationMessage(
          `Cherry-pick completed: ${pickedShas.length} applied, ${emptyShas.length} already applied or empty.`
        );
        await refreshPromise;
      }
}
