// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function handleDirectoryTimelineOpen(this: CommandController, arg?: unknown): Promise<void> {
  const targetUri = this.asFileResourceUri(arg);
      if (!targetUri) {
        void vscode.window.showWarningMessage(
          'Right-click a folder in the Explorer to view its timeline.'
        );
        return;
      }
  
      if (!(await this.git.isRepo())) {
        void vscode.window.showErrorMessage('Not inside a Git repository');
        return;
      }
  
      let stat: vscode.FileStat;
      try {
        stat = await vscode.workspace.fs.stat(targetUri);
      } catch {
        void vscode.window.showErrorMessage('Selected folder is no longer available.');
        return;
      }
  
      if ((stat.type & vscode.FileType.Directory) === 0) {
        void vscode.window.showWarningMessage(
          'Select a folder in the Explorer to view its timeline.'
        );
        return;
      }
  
      const gitRoot = await this.git.getGitRoot();
      const normalizedRoot = gitRoot.replace(/[\\/]+$/, '');
      const normalizedTarget = targetUri.fsPath.replace(/[\\/]+$/, '');
      const repoRelative =
        normalizedTarget === normalizedRoot ? '' : this.git.toRepoRelative(targetUri.fsPath);
      if (repoRelative === undefined) {
        void vscode.window.showErrorMessage('Not inside a Git repository');
        return;
      }
  
      await this.openDirectoryTimeline(repoRelative);
}
