// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleTagOpenCommits(this: CommandController, arg?: unknown): Promise<void> {
  const revision =
        this.toTagRevision(arg) ?? (await this.pickCommitSha('Pick tag or revision for details'));
      if (!revision) {
        return;
      }
  
      const tagRef = this.toTagRef(arg) ?? revision;
      await this.openRefCommits(`tag:${revision}`, `Tag: ${tagRef}`, revision);
}
