// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function handleRebaseConflict(this: CommandController): Promise<void> {
  void vscode.window.showWarningMessage(
        'There are some conflicts. You have to resolve them first.'
      );
      await this.openOperationConflictEditors('rebase');
}
