// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { SubmoduleTreeItem } from '../../providers/submoduleTreeProvider';
import { withSubmoduleProgress } from '../helpers/with-submodule-progress';

export async function handleSubmoduleSync(this: CommandController, arg?: unknown): Promise<void> {
  const item = arg instanceof SubmoduleTreeItem ? arg : undefined;
      if (!item) {
        return;
      }
      try {
        await withSubmoduleProgress(
          this.logger,
          {
            title: `Syncing submodule ${item.submodule.path}…`,
            autoShow: false,
            command: 'Submodule sync'
          },
          ({ sink, signal }) => this.git.syncSubmodule(item.submodule.path, false, { sink, signal })
        );
      } finally {
        await this.state.refreshSubmodules();
      }
}
