// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { GIT_COMMAND_PREFIX } from '../../config/commands';

export function legacyCommandId(this: CommandController, command: string): string | undefined {
  return command.startsWith(GIT_COMMAND_PREFIX)
        ? `intelliGit.${command.slice(GIT_COMMAND_PREFIX.length)}`
        : undefined;
}
