// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { BranchTreeItem } from '../../providers/branchTreeProvider';

export function normalizeBranchActionHubArg(this: CommandController, arg: unknown): string | undefined {
  if (arg instanceof BranchTreeItem) {
        return arg.branch.name;
      }
      if (typeof arg !== 'string') {
        return undefined;
      }
      const raw = arg.trim();
      return raw || undefined;
}
