// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function openBranchCommits(this: CommandController, branchName: string): Promise<void> {
  await this.openRefCommits(`branch:${branchName}`, `Branch: ${branchName}`, branchName);
}
