// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { CommitActionContext } from '../../providers/commitFilesTreeProvider';

export async function openCommitActionContextDiffs(this: CommandController, context: CommitActionContext): Promise<void> {
  const orderedPaths = [...new Set(context.filePaths)].sort((a, b) => a.localeCompare(b));
      if (context.kind === 'commit') {
        for (const filePath of orderedPaths) {
          await this.editor.openCommitFileDiffWithStatus(
            context.sha,
            filePath,
            context.fileStatuses?.[filePath]
          );
        }
        return;
      }
  
      if (context.kind === 'range') {
        for (const filePath of orderedPaths) {
          await this.editor.openCommitRangeFileDiff(context.fromRef, context.toRef, filePath, {
            fromLabel: context.fromLabel,
            toLabel: context.toLabel
          });
        }
        return;
      }
  
      for (const filePath of orderedPaths) {
        await this.editor.openWorkingTreeFileDiff(filePath, context.ref, context.refLabel, {
          preview: true,
          status: context.fileStatuses?.[filePath]
        });
      }
}
