// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { getConfigValue } from '../../configuration';
import { CommitListView } from '../../views/commitListView';

export async function openRefCommits(this: CommandController, id: string, title: string, ref: string): Promise<void> {
  const maxCommits = Math.max(1, getConfigValue<number>('maxGraphCommits', 200));
      const view = CommitListView.open(
        {
          id,
          title,
          hint: `Showing up to ${maxCommits} commits reachable from ${ref}. Filters update the table locally.`,
          branches: this.state.branches,
          commits: this.state.graph
        },
        {
          openCommitDetails: async (sha, subject) =>
            this.openCommitDetails(sha, subject, { allowToggle: true }),
          getCommitFiles: async (sha) => this.git.getFilesInCommit(sha),
          openFileDiff: async (sha, filePath) => this.editor.openCommitFileDiff(sha, filePath)
        }
      );
  
      view.setLoading(true);
      // Match Filter Graph's cached-state-first loading: refreshing refs can
      // include slow remote checks, but the selected ref is already known and
      // must not wait before its history query starts.
      void this.state.refreshBranches().catch((error) => {
        this.logger.info(
          `openRefCommits: refreshBranches failed: ${error instanceof Error ? error.message : String(error)}`
        );
      });
      try {
        const commits = await this.git.getGraph(maxCommits, 0, { branch: ref });
        view.update({
          id,
          title,
          hint: `Showing up to ${maxCommits} commits reachable from ${ref}. Filters update the table locally.`,
          branches: this.state.branches,
          commits
        });
      } finally {
        view.setLoading(false);
      }
}
