// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function openDiffWorkflow(this: CommandController): Promise<void> {
  const mode = await vscode.window.showQuickPick(
        ['Working tree vs HEAD', 'Index vs HEAD', 'Commit vs parent', 'Any two refs for one file'],
        { title: 'Open side-by-side diff' }
      );
  
      if (!mode) {
        return;
      }
  
      if (mode === 'Commit vs parent') {
        const sha = await this.pickCommitSha('Pick commit');
        if (!sha) {
          return;
        }
        await this.editor.openCommitFilesDiff(sha);
        return;
      }
  
      let leftRef = 'HEAD';
      let rightRef = 'WORKTREE';
  
      if (mode === 'Index vs HEAD') {
        leftRef = 'HEAD';
        rightRef = 'INDEX';
      }
  
      if (mode === 'Any two refs for one file') {
        leftRef =
          (
            await vscode.window.showInputBox({
              title: 'Left ref',
              placeHolder: 'e.g. main, HEAD~1, abc1234'
            })
          )?.trim() ?? '';
        rightRef =
          (
            await vscode.window.showInputBox({
              title: 'Right ref',
              placeHolder: 'e.g. feature/x, HEAD, def5678'
            })
          )?.trim() ?? '';
  
        if (!leftRef || !rightRef) {
          return;
        }
      }
  
      const filePath = await this.pickFileFromWorkspace('Pick file to diff');
      if (!filePath) {
        return;
      }
  
      await this.editor.openDiffForFile({
        path: filePath,
        leftRef,
        rightRef,
        title: `${mode} · ${filePath}`
      });
}
