// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function openOperationConflictEditors(this: CommandController, operation: 'cherry-pick' | 'merge' | 'rebase'): Promise<void> {
  const conflicts =
        this.state.conflicts.length > 0 ? this.state.conflicts : await this.git.getMergeConflicts();
      if (conflicts.length === 0) {
        await vscode.commands.executeCommand('workbench.view.scm');
        return;
      }
  
      let openedCount = 0;
      for (const conflict of conflicts) {
        try {
          await this.editor.openMergeConflict(conflict.path);
          openedCount += 1;
        } catch (error) {
          this.logger.warn(
            `Failed to open merge editor for ${operation} conflict file ${conflict.path}: ${String(error)}`
          );
        }
      }
  
      if (openedCount < conflicts.length) {
        await vscode.commands.executeCommand('workbench.view.scm');
      }
}
