// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function orderShasForCherryPick(this: CommandController, shas: string[]): Promise<string[]> {
  if (shas.length <= 1) {
        return shas;
      }
      try {
        const timestamps = await this.git.getCommitTimestamps(shas);
        return [...shas].sort((a, b) => (timestamps.get(a) ?? 0) - (timestamps.get(b) ?? 0));
      } catch (error) {
        this.logger.error(
          'Could not determine commit order for cherry-pick; using selection order.',
          error
        );
        return shas;
      }
}
