// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function pickConflictPath(this: CommandController, title: string): Promise<string | undefined> {
  const conflicts =
        this.state.conflicts.length > 0 ? this.state.conflicts : await this.git.getMergeConflicts();
      if (conflicts.length === 0) {
        void vscode.window.showInformationMessage('No conflicted files.');
        return undefined;
      }
      const picked = await vscode.window.showQuickPick(
        conflicts.map((c) => ({ label: c.path, description: c.status })),
        { title }
      );
      return picked?.label;
}
