// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function pickFileFromWorkspace(this: CommandController, title: string): Promise<string | undefined> {
  const files = await vscode.workspace.findFiles('**/*', '**/.git/**', 500);
      const picked = await vscode.window.showQuickPick(
        files
          .map((uri) => this.git.toRepoRelative(uri.fsPath))
          .filter((rel): rel is string => Boolean(rel))
          .map((label) => ({ label })),
        {
          title,
          matchOnDescription: true
        }
      );
  
      return picked?.label;
}
