// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function pickPatchOutputTarget(this: CommandController, title: string): Promise<'clipboard' | 'file' | undefined> {
  const picked = await vscode.window.showQuickPick(
        [
          {
            label: 'Save to patch file',
            description: 'Write patch text to a .patch/.diff file',
            target: 'file' as const
          },
          {
            label: 'Copy patch to clipboard',
            description: 'Copy patch text so you can paste it anywhere',
            target: 'clipboard' as const
          }
        ],
        {
          title
        }
      );
      return picked?.target;
}
