// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';
import { resolveWorktreeTargetPath } from '../../services/worktreeTargetPath';
import * as path from 'path';

export async function pickWorktreeTargetPath(this: CommandController, title: string, refName: string): Promise<string | undefined> {
  const gitRoot = await this.git.getGitRoot();
      const picked = await vscode.window.showOpenDialog({
        title,
        openLabel: 'Use Folder',
        canSelectFiles: false,
        canSelectFolders: true,
        canSelectMany: false,
        defaultUri: vscode.Uri.file(path.dirname(gitRoot))
      });
  
      const selectedFolderPath = picked?.[0]?.fsPath;
      if (!selectedFolderPath) {
        return undefined;
      }
  
      const resolved = await resolveWorktreeTargetPath(selectedFolderPath, gitRoot, refName);
      if (!resolved.ok) {
        void vscode.window.showErrorMessage(resolved.message);
        return undefined;
      }
  
      return resolved.targetPath;
}
