// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { pickRevisionToCompare, RevisionSelection } from '../../views/revisionPicker';

export async function pickWorktreeRevision(this: CommandController, title: string): Promise<RevisionSelection | undefined> {
  return pickRevisionToCompare(
        this.git,
        () => this.state.branches,
        () => this.state.tags,
        () => this.state.refreshBranches(),
        {
          title,
          placeholder: 'Select a local branch, remote branch, tag, or type a revision',
          emptyPlaceholder: 'No branches or tags found - type a revision',
          loadingPlaceholder: 'Loading branches and tags...',
          refreshingPlaceholder: 'Refreshing branches and tags...',
          allowTypedRevision: true
        }
      );
}
