// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export function pickConflictPathArg(this: CommandController, arg: unknown): string | undefined {
  if (typeof arg === 'string' && arg.trim()) {
        return arg.trim();
      }
      return undefined;
}
