// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function pickPatchSource(this: CommandController): Promise<{ kind: 'clipboard' | 'file' } | undefined> {
  const picked = await vscode.window.showQuickPick(
        [
          {
            label: 'Apply patch from clipboard',
            description: 'Use patch text currently in clipboard',
            source: 'clipboard' as const
          },
          {
            label: 'Apply patch from file',
            description: 'Pick a .patch/.diff file from disk',
            source: 'file' as const
          }
        ],
        {
          title: 'Apply Patch'
        }
      );
      return picked ? { kind: picked.source } : undefined;
}
