// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function readPatchFromFile(this: CommandController): Promise<string | undefined> {
  const picked = await vscode.window.showOpenDialog({
        title: 'Select Patch File',
        canSelectFiles: true,
        canSelectFolders: false,
        canSelectMany: false,
        filters: {
          Patch: ['patch', 'diff'],
          Text: ['txt']
        }
      });
      const uri = picked?.[0];
      if (!uri) {
        return undefined;
      }
  
      const bytes = await vscode.workspace.fs.readFile(uri);
      return Buffer.from(bytes).toString('utf8');
}
