// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export function resolveCommitSubject(this: CommandController, sha: string, argValue: unknown, selectedArgValue: unknown): string {
  const candidates = [argValue, ...(Array.isArray(selectedArgValue) ? selectedArgValue : [])];
      for (const candidate of candidates) {
        if (this.toCommitSha(candidate) !== sha) {
          continue;
        }
        const subject = this.toCommitSubject(candidate);
        if (subject) {
          return subject;
        }
      }
      return this.state.graph.find((commit) => commit.sha === sha)?.subject ?? sha;
}
