// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export function resolveBranchNameForActionHub(this: CommandController, rawBranchName: string): string | undefined {
  const exactMatch = this.state.branches.find((branch) => branch.name === rawBranchName);
      if (exactMatch) {
        return exactMatch.name;
      }
  
      const uniqueLocalShortMatch = this.state.branches.filter(
        (branch) => branch.type === 'local' && branch.shortName === rawBranchName
      );
      if (uniqueLocalShortMatch.length === 1) {
        return uniqueLocalShortMatch[0].name;
      }
  
      const uniqueShortMatch = this.state.branches.filter(
        (branch) => branch.shortName === rawBranchName
      );
      if (uniqueShortMatch.length === 1) {
        return uniqueShortMatch[0].name;
      }
  
      return undefined;
}
