// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';
import { CommitFileTreeItem, CommitFolderTreeItem, CommitRangeFileTreeItem, CommitSelectableFileTreeItem, WorkingTreeCompareFileTreeItem } from '../../providers/commitFilesTreeProvider';
import { GraphCommitFileTreeItem } from '../../providers/graphTreeProvider';
import { SelectedChangeTarget } from '../types';

export async function resolveSelectedCommitFiles(this: CommandController, arg: unknown, selectedArg: unknown): Promise<SelectedChangeTarget | undefined> {
  const selectedItems = this.toSelectedItems(arg, selectedArg);
      if (
        selectedItems.length > 0 &&
        (selectedItems[0] instanceof CommitFileTreeItem ||
          selectedItems[0] instanceof CommitRangeFileTreeItem ||
          selectedItems[0] instanceof WorkingTreeCompareFileTreeItem ||
          selectedItems[0] instanceof CommitFolderTreeItem)
      ) {
        const context = this.commitFilesView.getCommitActionContext(
          selectedItems as CommitSelectableFileTreeItem[]
        );
        if (!context || context.filePaths.length === 0) {
          return undefined;
        }
        return this.toSelectedChangeTarget(context);
      }
  
      const graphItems = selectedItems.filter(
        (item): item is GraphCommitFileTreeItem => item instanceof GraphCommitFileTreeItem
      );
      if (graphItems.length === 0) {
        return undefined;
      }
  
      const commitShas = [...new Set(graphItems.map((item) => item.commit.sha))];
      if (commitShas.length !== 1) {
        void vscode.window.showWarningMessage('Select files from a single commit only.');
        return undefined;
      }
  
      const sha = commitShas[0];
      const commit = graphItems[0].commit;
      const filePaths = [...new Set(graphItems.map((item) => item.filePath))].sort((a, b) =>
        a.localeCompare(b)
      );
      if (filePaths.length === 0) {
        return undefined;
      }
  
      const canRevert = await this.git.isCommitInCurrentBranch(sha);
      return {
        kind: 'commit',
        sha,
        subject: commit.subject,
        filePaths,
        canRevert,
        canCherryPick: !canRevert,
        canCreatePatch: !canRevert,
        detailLabel: `Commit: ${sha}`,
        shortLabel: sha.slice(0, 8)
      };
}
