// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function showRebaseProgressFeedback(this: CommandController): Promise<void> {
  const state = this.state.operationState;
      if (state.kind !== 'rebase') {
        void vscode.window.showInformationMessage('Rebase completed successfully.');
        return;
      }
  
      const progress =
        state.stepCurrent && state.stepTotal ? ` (${state.stepCurrent}/${state.stepTotal})` : '';
      const conflicts =
        this.state.conflicts.length > 0 ? this.state.conflicts : await this.git.getMergeConflicts();
      if (conflicts.length > 0) {
        await this.handleRebaseConflict();
        return;
      }
  
      void vscode.window.showInformationMessage(
        `Rebase is still in progress${progress}. Continue to process remaining commits or Abort.`
      );
}
