// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';
import { convertToSshUrl } from '../../services/gitParsing';

export async function sshPull(this: CommandController, targetHost: string | 'prompt'): Promise<void> {
  const remoteUrls = await this.git.getRemoteFetchUrls();
      if (remoteUrls.size === 0) {
        void vscode.window.showErrorMessage('No remotes found in this repository.');
        return;
      }
  
      const remoteItems = [...remoteUrls.entries()].map(([name, url]) => ({
        label: name,
        description: url
      }));
  
      const picked = await vscode.window.showQuickPick(remoteItems, {
        title: 'Select remote to switch to SSH',
        placeHolder: 'Pick a remote'
      });
      if (!picked) {
        return;
      }
  
      const remoteName = picked.label;
      const currentUrl = remoteUrls.get(remoteName);
      if (currentUrl === undefined) {
        return;
      }
  
      let host: string;
      if (targetHost === 'prompt') {
        const input = await vscode.window.showInputBox({
          title: 'Force SSH Pull (Custom Server)',
          prompt: 'Enter SSH hostname',
          placeHolder: 'git.mycompany.com',
          validateInput: (v) => (v.trim() ? undefined : 'SSH hostname is required')
        });
        if (!input) {
          return;
        }
        host = input.trim();
      } else {
        host = targetHost;
      }
  
      const sshUrl = convertToSshUrl(currentUrl, host);
      if (sshUrl !== null) {
        await this.git.setRemoteUrl(remoteName, sshUrl);
      }
  
      await this.git.pull();
      await this.state.refreshAll();
}
