// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function startMergeOperation(this: CommandController, run: () => Promise<void>): Promise<void> {
  try {
        await run();
      } catch (error) {
        const issue = this.classifyMergeIssue(error);
        if (issue.kind === 'conflict') {
          await this.handleOperationConflict('merge', this.state.refreshAll());
          return;
        }
        throw error;
      }
  
      await this.state.refreshAll();
}
