// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export function toBranchName(this: CommandController, value: unknown): string | undefined {
  const item = this.asBranchItem(value);
      if (item) {
        return item.branch.name;
      }
      if (typeof value !== 'string') {
        return undefined;
      }
      const raw = value.trim();
      if (!raw) {
        return undefined;
      }
      return this.resolveBranchNameForActionHub(raw) ?? raw;
}
