// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export function toCommitSha(this: CommandController, value: unknown): string | undefined {
  if (typeof value === 'string') {
        const trimmed = value.trim();
        return trimmed || undefined;
      }
      if (
        typeof value === 'object' &&
        value !== null &&
        'sha' in value &&
        typeof (value as { sha?: unknown }).sha === 'string'
      ) {
        const sha = ((value as { sha: string }).sha ?? '').trim();
        if (sha) {
          return sha;
        }
      }
      const tag = this.asTagItem(value)?.tag;
      return this.asGraphItem(value)?.commit.sha ?? tag?.sha ?? tag?.name;
}
