// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export function toCommitSubject(this: CommandController, value: unknown): string | undefined {
  if (this.asGraphItem(value)) {
        const subject = this.asGraphItem(value)?.commit.subject?.trim();
        return subject || undefined;
      }
      if (
        typeof value === 'object' &&
        value !== null &&
        'subject' in value &&
        typeof (value as { subject?: unknown }).subject === 'string'
      ) {
        const subject = ((value as { subject: string }).subject ?? '').trim();
        return subject || undefined;
      }
      return undefined;
}
