// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export function toExplorerResourceUris(this: CommandController, arg: unknown, selectedArg: unknown): vscode.Uri[] {
  const selectedUris = Array.isArray(selectedArg)
        ? selectedArg
            .map((item) => this.asFileResourceUri(item))
            .filter((uri): uri is vscode.Uri => Boolean(uri))
        : [];
      const primary = this.asFileResourceUri(arg);
      const combined = primary ? [primary, ...selectedUris] : selectedUris;
      const uniqueByPath = new Map<string, vscode.Uri>();
      for (const uri of combined) {
        uniqueByPath.set(uri.fsPath, uri);
      }
      return [...uniqueByPath.values()];
}
