// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export function toGraphCommitShas(this: CommandController, arg: unknown, selectedArg: unknown): string[] {
  const selectedItems = Array.isArray(selectedArg) ? selectedArg : [];
      const fromSelected = selectedItems
        .map((item) => this.asGraphItem(item)?.commit.sha ?? this.toCommitSha(item))
        .map((value) => (typeof value === 'string' ? value.trim() : ''))
        .filter((value): value is string => Boolean(value));
      if (fromSelected.length > 0) {
        return [...new Set(fromSelected)];
      }
      const primary = this.toCommitSha(arg);
      return primary ? [primary] : [];
}
