// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export function toRepoFilePath(this: CommandController, value: unknown): string | undefined {
  if (typeof value === 'string') {
        const trimmed = value.trim();
        return trimmed || undefined;
      }
  
      const filePath =
        this.asGraphFileItem(value)?.filePath ??
        this.asCommitViewFileItem(value)?.filePath ??
        this.asRevisionViewFileItem(value)?.filePath;
      if (filePath) {
        return filePath;
      }
  
      const uri = this.asFileResourceUri(value);
      if (!uri) {
        return undefined;
      }
  
      return this.git.toRepoRelative(uri.fsPath);
}
