// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { SelectableChangeTreeItem } from '../types';

export function toSelectedItems(this: CommandController, arg: unknown, selectedArg: unknown): SelectableChangeTreeItem[] {
  const selectedList = Array.isArray(selectedArg) ? selectedArg : [];
      const first = this.extractSelectableItem(arg);
      const fromSelected = selectedList
        .map((item) => this.extractSelectableItem(item))
        .filter((item): item is SelectableChangeTreeItem => Boolean(item));
  
      const all = [...fromSelected];
      if (first) {
        all.unshift(first);
      }
  
      return [...new Set(all)];
}
