// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import { CommitActionContext } from '../../providers/commitFilesTreeProvider';
import { SelectedChangeTarget } from '../types';

export function toSelectedChangeTarget(this: CommandController, context: CommitActionContext): SelectedChangeTarget {
  if (context.kind === 'commit') {
        return {
          kind: 'commit',
          sha: context.sha,
          subject: context.subject,
          filePaths: context.filePaths,
          canRevert: context.canRevertSelected,
          canCherryPick: context.canCherryPickSelected,
          canCreatePatch: context.canCreatePatchSelected,
          detailLabel: `Commit: ${context.sha}`,
          shortLabel: context.sha.slice(0, 8)
        };
      }
  
      if (context.kind === 'workingTreeCompare') {
        return {
          kind: 'workingTreeCompare',
          ref: context.ref,
          refLabel: context.refLabel,
          filePaths: context.filePaths,
          canRevert: context.canRevertSelected,
          canCherryPick: context.canCherryPickSelected,
          canCreatePatch: context.canCreatePatchSelected,
          detailLabel: `Compare with revision: ${context.refLabel}`,
          shortLabel: context.refLabel
        };
      }
  
      return {
        kind: 'range',
        fromRef: context.fromRef,
        toRef: context.toRef,
        fromLabel: context.fromLabel,
        toLabel: context.toLabel,
        filePaths: context.filePaths,
        canRevert: context.canRevertSelected,
        canCherryPick: context.canCherryPickSelected,
        canCreatePatch: context.canCreatePatchSelected,
        detailLabel: `Range: ${context.fromLabel}..${context.toLabel}`,
        shortLabel: `${context.fromLabel}..${context.toLabel}`
      };
}
