// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export function toTagRevision(this: CommandController, value: unknown): string | undefined {
  const tag = this.asTagItem(value)?.tag;
      return tag?.sha ?? tag?.name;
}
