// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export function toTagRef(this: CommandController, value: unknown): string | undefined {
  return this.asTagItem(value)?.tag.name;
}
