// Generated by split-class.mjs
import type { GitService } from './index';

export async function addDetachedWorktree(this: GitService, worktreePath: string, ref: string): Promise<void> {
  await this.runGit(['worktree', 'add', '--detach', worktreePath, ref]);
}
