// Generated by split-class.mjs
import type { GitService } from './index';

export async function addRemote(this: GitService, remoteName: string, remoteUrl: string): Promise<void> {
  await this.runGit(['remote', 'add', remoteName, remoteUrl]);
}
