// Generated by split-class.mjs
import type { GitService } from './index';

export async function addWorktreeBranch(this: GitService, worktreePath: string, branch: string, base?: string): Promise<void> {
  const args = ['worktree', 'add', '-b', branch, worktreePath];
      if (base) {
        args.push(base);
      }
      await this.runGit(args);
}
