// Generated by split-class.mjs
import type { GitService } from './index';

export async function applyStash(this: GitService, ref: string, pop = false): Promise<void> {
  await this.runGit(['stash', pop ? 'pop' : 'apply', ref]);
}
