// Generated by split-class.mjs
import type { GitService } from './index';
import * as vscode from 'vscode';

export async function applyMergeEditorColumnLayout(this: GitService): Promise<void> {
  const commandCandidates = [
        'merge.columnLayout',
        'mergeEditor.setColumnLayout',
        'workbench.action.mergeEditor.setColumnLayout'
      ];
      for (const cmd of commandCandidates) {
        try {
          await vscode.commands.executeCommand(cmd);
          return;
        } catch {
          // try next candidate
        }
      }
}
