// Generated by split-class.mjs
import type { GitService } from './index';
import * as vscode from 'vscode';

export async function checkoutBranch(this: GitService, branch: string): Promise<void> {
  const repository = await this.getVsCodeRepository();
      if (repository) {
        this.logger.info(`vscode.git checkout ${branch}`);
        await repository.checkout(branch);
        return;
      }
      await this.runGit(['checkout', branch]);
}
