// Generated by split-class.mjs
import type { GitService } from './index';

export async function cherryPickAbort(this: GitService): Promise<void> {
  await this.runGit(['cherry-pick', '--abort']);
}
