// Generated by split-class.mjs
import type { GitService } from './index';

export async function cherryPickContinue(this: GitService): Promise<void> {
  await this.runGit(['-c', 'core.editor=true', 'cherry-pick', '--continue']);
}
