// Generated by split-class.mjs
import type { GitService } from './index';

export async function cherryPickRange(this: GitService, fromExclusive: string, toInclusive: string): Promise<void> {
  await this.runGit(['cherry-pick', `${fromExclusive}..${toInclusive}`]);
}
