// Generated by split-class.mjs
import type { GitService } from './index';

export async function cherryPickCommitFiles(this: GitService, ref: string, filePaths: string[]): Promise<void> {
  await this.applyCommitFilesPatch(ref, filePaths, false);
}
