// Generated by split-class.mjs
import type { GitService } from './index';

export async function cherryPick(this: GitService, ref: string): Promise<void> {
  await this.runGit(['cherry-pick', ref]);
}
