// Generated by split-class.mjs
import type { GitService } from './index';
import * as vscode from 'vscode';

export async function commit(this: GitService, message: string): Promise<void> {
  const repository = await this.getVsCodeRepository();
      if (repository) {
        this.logger.info('vscode.git commit -m <message>');
        await repository.commit(message);
        return;
      }
      await this.runGit(['commit', '-m', message]);
}
