// Generated by split-class.mjs
import type { GitService } from './index';
import * as vscode from 'vscode';

export async function createStash(this: GitService, message: string, options: { includeUntracked: boolean; keepIndex: boolean }): Promise<void> {
  const repository = await this.getVsCodeRepository();
      if (repository && !options.keepIndex) {
        this.logger.info(`vscode.git createStash ${message}`);
        await repository.createStash({ message, includeUntracked: options.includeUntracked });
        return;
      }
  
      const args = ['stash', 'push', '-m', message];
      if (options.includeUntracked) {
        args.push('-u');
      }
      if (options.keepIndex) {
        args.push('--keep-index');
      }
      await this.runGit(args);
}
