// Generated by split-class.mjs
import type { GitService } from './index';
import { SpawnGitStreamingResult } from '../submoduleService';
import { SubmoduleLogSink } from '../submoduleLogSink';

export async function deinitSubmodule(this: GitService, submodulePath: string, force = false, opts: { sink?: SubmoduleLogSink; signal?: AbortSignal } = {}): Promise<SpawnGitStreamingResult> {
  return this.submoduleSvc.deinitSubmodule(submodulePath, force, opts);
}
