// Generated by split-class.mjs
import type { GitService } from './index';

export async function deleteRemote(this: GitService, remoteName: string): Promise<void> {
  await this.runGit(['remote', 'remove', remoteName]);
}
