// Generated by split-class.mjs
import type { GitService } from './index';

export async function dropStash(this: GitService, ref: string): Promise<void> {
  await this.runGit(['stash', 'drop', ref]);
}
