// Generated by split-class.mjs
import type { GitService } from './index';
import { GraphCommit } from '../../types';
const FIELD_SEPARATOR = '|~|';
const RECORD_SEPARATOR = '|#|';
function parseGraphRows(raw: string): GraphCommit[] {
  return raw
    .split(RECORD_SEPARATOR)
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => {
      const [graph, sha, shortSha, parentsRaw, refsRaw, author, date, subject] =
        line.split(FIELD_SEPARATOR);
      return {
        graph,
        sha,
        shortSha,
        parents: parentsRaw?.split(' ').filter(Boolean) ?? [],
        refs: refsRaw
          ? refsRaw
              .split(',')
              .map((r) => r.trim())
              .filter(Boolean)
          : [],
        author,
        date,
        subject
      };
    });
}

export async function fileHistory(this: GitService, path: string): Promise<GraphCommit[]> {
  const format = `%m${FIELD_SEPARATOR}%H${FIELD_SEPARATOR}%h${FIELD_SEPARATOR}%P${FIELD_SEPARATOR}%D${FIELD_SEPARATOR}%an${FIELD_SEPARATOR}%aI${FIELD_SEPARATOR}%s${RECORD_SEPARATOR}`;
      const result = await this.runGit([
        'log',
        '--date=iso-strict',
        '--follow',
        `--format=${format}`,
        '--',
        path
      ]);
      return parseGraphRows(result.stdout);
}
