// Generated by split-class.mjs
import type { GitService } from './index';

export async function fileBlame(this: GitService, path: string): Promise<string> {
  const result = await this.runGit(['blame', '--', path]);
      return result.stdout;
}
