// Generated by split-class.mjs
import type { GitService } from './index';
import * as vscode from 'vscode';

export async function generateCommitMessage(this: GitService, token?: vscode.CancellationToken): Promise<string> {
  let diff = '';
      try {
        const staged = await this.runGit(['diff', '--staged']);
        diff = staged.stdout;
      } catch {
        /* ignore */
      }
  
      if (!diff.trim()) {
        try {
          const unstaged = await this.runGit(['diff']);
          diff = unstaged.stdout;
        } catch {
          /* ignore */
        }
      }
  
      if (!diff.trim()) {
        throw new Error('No changes to generate a commit message from.');
      }
  
      const maxLen = 8000;
      const truncated =
        diff.length > maxLen ? diff.slice(0, maxLen) + '\n... (diff truncated)' : diff;
  
      const preferredFamilies = ['gpt-5-mini', 'gpt-4.1', 'gpt-4o', 'gpt-4', 'claude-3.5-sonnet'];
      let model: vscode.LanguageModelChat | undefined;
      for (const family of preferredFamilies) {
        const [m] = await vscode.lm.selectChatModels({ family });
        if (m) {
          model = m;
          break;
        }
      }
      if (!model) {
        const [any] = await vscode.lm.selectChatModels();
        model = any;
      }
      if (!model) {
        throw new Error(
          'No AI model available. Install GitHub Copilot or another AI extension to enable this feature.'
        );
      }
  
      const cts = new vscode.CancellationTokenSource();
      if (token) {
        token.onCancellationRequested(() => cts.cancel());
      }
      const messages = [
        vscode.LanguageModelChatMessage.User(
          `Write a concise git commit message (imperative mood, 50 chars or less for the subject line) for this diff. Output only the commit message, nothing else:\n\n${truncated}`
        )
      ];
  
      const response = await model.sendRequest(messages, {}, cts.token);
      let result = '';
      for await (const chunk of response.text) {
        result += chunk;
      }
      return result.trim();
}
