// Generated by split-class.mjs
import { GitService } from './index';
import { BranchRef } from '../../types';

export async function getBranches(this: GitService): Promise<BranchRef[]> {
  const remoteUrls = await this.getRemoteFetchUrls();
      const [locals, remotes] = await Promise.all([
        this.getLocalBranches(),
        this.getRemoteBranches(remoteUrls)
      ]);
      return [...locals, ...remotes].sort(GitService.BRANCH_SORT_COMPARATOR);
}
