// Generated by split-class.mjs
import type { GitService } from './index';
import { CommitDetails } from '../../types';
function parseShortStat(
  raw: string
): { files: number; insertions: number; deletions: number } | undefined {
  const line = raw
    .split('\n')
    .map((value) => value.trim())
    .find((value) => value.length > 0);

  if (!line) {
    return undefined;
  }

  const filesMatch = line.match(/(\d+)\s+files?\s+changed/);
  const insertionsMatch = line.match(/(\d+)\s+insertions?\(\+\)/);
  const deletionsMatch = line.match(/(\d+)\s+deletions?\(-\)/);

  return {
    files: Number(filesMatch?.[1] ?? 0),
    insertions: Number(insertionsMatch?.[1] ?? 0),
    deletions: Number(deletionsMatch?.[1] ?? 0)
  };
}

export async function getCommitDetails(this: GitService, sha: string): Promise<CommitDetails> {
  const [commit] = await this.getGraph(1, 0, { branch: sha });
      const bodyResult = await this.runGit(['show', '--quiet', '--format=%B', sha]);
      const nameStatus = await this.runGit(['show', '--name-status', '--format=', sha]);
      const shortStatResult = await this.runGit(['show', '--shortstat', '--format=', sha]);
      const changedFiles = nameStatus.stdout
        .split('\n')
        .map((line) => line.trim())
        .filter(Boolean)
        .map((line) => {
          const [status, path] = line.split('\t');
          return { status, path };
        });
  
      const stats = parseShortStat(shortStatResult.stdout);
  
      return {
        commit: {
          ...commit,
          stats
        },
        body: bodyResult.stdout.trim(),
        changedFiles
      };
}
