// Generated by split-class.mjs
import type { GitService } from './index';

export async function getCurrentHeadSha(this: GitService): Promise<string> {
  const repository = await this.getVsCodeRepository();
      if (repository?.state.HEAD?.commit) {
        return repository.state.HEAD.commit;
      }
      const result = await this.runGit(['rev-parse', 'HEAD']);
      return result.stdout.trim();
}
