// Generated by split-class.mjs
import type { GitService } from './index';
import { WorkingTreeChange } from '../../types';
import { parsePorcelainStatusZ } from '../gitParsing';

export async function getChangedFiles(this: GitService): Promise<WorkingTreeChange[]> {
  const vscodeGitChanges = await this.getChangedFilesFromVsCodeGit();
      if (vscodeGitChanges) {
        return vscodeGitChanges;
      }
  
      const result = await this.runGit(['status', '--porcelain=v1', '-z']);
      return parsePorcelainStatusZ(result.stdout);
}
