// Generated by split-class.mjs
import type { GitService } from './index';

export async function getCurrentBranch(this: GitService): Promise<string> {
  const repository = await this.getVsCodeRepository();
      if (repository?.state.HEAD?.name) {
        return repository.state.HEAD.name;
      }
      const result = await this.runGit(['rev-parse', '--abbrev-ref', 'HEAD']);
      return result.stdout.trim();
}
