// Generated by split-class.mjs
import type { GitService } from './index';
import { CommitFileChange } from '../../types';

export async function getFilesInCommitWithStatus(this: GitService, sha: string): Promise<CommitFileChange[]> {
  const result = await this.runGit(['show', '--name-status', '--pretty=format:', sha]);
      return result.stdout
        .split('\n')
        .map((line) => line.trim())
        .filter(Boolean)
        .map((line) => {
          const parts = line.split('\t').filter(Boolean);
          const statusRaw = parts[0] ?? '';
          const status = (statusRaw ?? '').trim();
          const normalizedStatus = status[0]?.toUpperCase();
          const oldPath =
            normalizedStatus === 'R' || normalizedStatus === 'C'
              ? (parts[1] ?? '').trim()
              : undefined;
          const path = (parts.at(-1) ?? '').trim();
          return { status, path, oldPath };
        })
        .filter((entry) => Boolean(entry.path));
}
