// Generated by split-class.mjs
import type { GitService } from './index';

export async function getFilesInCommit(this: GitService, sha: string): Promise<string[]> {
  const entries = await this.getFilesInCommitWithStatus(sha);
      return entries.map((entry) => entry.path);
}
