// Generated by split-class.mjs
import type { GitService } from './index';

export async function getFilesAtRevision(this: GitService, ref: string): Promise<string[]> {
  const result = await this.runGit(['ls-tree', '-r', '--name-only', ref]);
      return result.stdout
        .split('\n')
        .map((line) => line.trim())
        .filter(Boolean);
}
