// Generated by split-class.mjs
import type { GitService } from './index';

export async function getFilesChangedBetween(this: GitService, leftRef: string, rightRef: string): Promise<string[]> {
  const result = await this.runGit(['diff', '--name-only', `${leftRef}...${rightRef}`]);
      return result.stdout
        .split('\n')
        .map((line) => line.trim())
        .filter(Boolean);
}
