// Generated by split-class.mjs
import type { GitService } from './index';
import { WorkingTreeFileChange } from '../../types';
import { parseNameStatusZ } from '../gitParsing';
import * as path from 'path';

export async function getFilesChangedBetweenWorkingTreeAndRef(this: GitService, ref: string, scopePath?: string): Promise<WorkingTreeFileChange[]> {
  const scopeArgs = scopePath ? ['--', scopePath] : [];
  
      // Tracked changes
      const trackedResult = await this.runGit(['diff', '--name-status', '-z', ref, ...scopeArgs]);
      const trackedEntries = parseNameStatusZ(trackedResult.stdout).map(
        (entry): WorkingTreeFileChange => ({
          status: entry.status,
          path: entry.path,
          untracked: false
        })
      );
  
      // Untracked files
      const untrackedResult = await this.runGit([
        'ls-files',
        '--others',
        '--exclude-standard',
        '-z',
        ...scopeArgs
      ]);
      const untrackedEntries: WorkingTreeFileChange[] = untrackedResult.stdout
        .split('\0')
        .filter((p) => p.length > 0)
        .map((p): WorkingTreeFileChange => ({ status: 'A', path: p, untracked: true }));
  
      // Merge: prefer tracked entry when path appears in both
      const trackedPaths = new Set(trackedEntries.map((e) => e.path));
      const merged = [
        ...trackedEntries,
        ...untrackedEntries.filter((e) => !trackedPaths.has(e.path))
      ];
  
      // Stable sort by path
      merged.sort((a, b) => a.path.localeCompare(b.path));
      return merged;
}
