// Generated by split-class.mjs
import type { GitService } from './index';

export async function getFileStageContent(this: GitService, stage: 1 | 2 | 3, filePath: string): Promise<string> {
  const result = await this.runGit(['show', `:${stage}:${filePath}`]);
      return result.stdout;
}
