// Generated by split-class.mjs
import type { GitService } from './index';
import { CommitFilters, GraphCommit } from '../../types';
const FIELD_SEPARATOR = '|~|';
const RECORD_SEPARATOR = '|#|';

export async function getGraph(this: GitService, maxCount: number, skip = 0, filters?: CommitFilters): Promise<GraphCommit[]> {
  const format = ['%m', '%H', '%h', '%P', '%D', '%an', '%aI', '%s'].join(FIELD_SEPARATOR);
  
      const args = [
        'log',
        '--date=iso-strict',
        '--decorate=full',
        `--max-count=${maxCount}`,
        `--format=${format}${RECORD_SEPARATOR}`
      ];
      if (skip > 0) {
        args.push(`--skip=${skip}`);
      }
  
      if (filters?.branch) {
        const branchKeyword = filters.branch.trim();
        const exactBranchRef = await this.resolveExactBranchRef(branchKeyword);
        if (exactBranchRef) {
          args.push(exactBranchRef);
        } else {
          args.push(`--branches=*${branchKeyword}*`, `--remotes=*${branchKeyword}*`);
        }
      } else {
        args.push('--all');
      }
      if (filters?.author) {
        args.push(`--author=${filters.author}`);
      }
      if (filters?.message) {
        const sha = await this.resolveShaFilter(filters.message);
        if (sha) {
          args.push(sha);
        } else {
          args.push(`--grep=${filters.message}`);
        }
      }
      if (filters?.since) {
        args.push(`--since=${filters.since}`);
      }
      if (filters?.until) {
        args.push(`--until=${filters.until}`);
      }
  
      const result = await this.runGit(args);
  
      return result.stdout
        .split(RECORD_SEPARATOR)
        .map((line) => line.trim())
        .filter(Boolean)
        .map((line) => {
          const [graph, sha, shortSha, parentsRaw, refsRaw, author, date, subject] =
            line.split(FIELD_SEPARATOR);
          const parents = parentsRaw?.split(' ').filter(Boolean) ?? [];
          const refs = refsRaw
            ? refsRaw
                .split(',')
                .map((ref) => ref.trim())
                .filter(Boolean)
            : [];
          return {
            graph,
            sha,
            shortSha,
            parents,
            refs,
            author,
            date,
            subject
          } as GraphCommit;
        });
}
