// Generated by split-class.mjs
import type { GitService } from './index';

export async function getHeadCommitMessage(this: GitService): Promise<string> {
  const result = await this.runGit(['log', '-1', '--pretty=%B']);
      return result.stdout.trim();
}
