// Generated by split-class.mjs
import { GitService } from './index';
import { BranchRef } from '../../types';
const RECORD_SEPARATOR = '|#|';

export async function getLocalBranches(this: GitService): Promise<BranchRef[]> {
  const result = await this.runGit([
        'for-each-ref',
        `--format=${GitService.BRANCH_FORMAT}${RECORD_SEPARATOR}`,
        'refs/heads'
      ]);
      return this.parseBranchLines(result.stdout, new Map()).sort(GitService.BRANCH_SORT_COMPARATOR);
}
