// Generated by split-class.mjs
import type { GitService } from './index';
import { MergeConflictFile } from '../../types';

export async function getMergeConflicts(this: GitService): Promise<MergeConflictFile[]> {
  const result = await this.runGit(['diff', '--name-status', '--diff-filter=U']);
      return result.stdout
        .split('\n')
        .map((line) => line.trim())
        .filter(Boolean)
        .map((line) => {
          const [status, path] = line.split('\t');
          return { status, path };
        });
}
