// Generated by split-class.mjs
import type { GitService } from './index';
import * as vscode from 'vscode';
import { GitOperationState } from '../../types';
import * as fs from 'fs';

export async function getOperationState(this: GitService): Promise<GitOperationState> {
  const gitDir = await this.getGitDir();
      if (!gitDir) {
        return { kind: 'none' };
      }
  
      const readFile = async (relative: string): Promise<string | undefined> => {
        try {
          const uri = vscode.Uri.file(`${gitDir}/${relative}`);
          const bytes = await vscode.workspace.fs.readFile(uri);
          return Buffer.from(bytes).toString('utf8').trim();
        } catch {
          return undefined;
        }
      };
  
      const exists = async (relative: string): Promise<boolean> => {
        try {
          await vscode.workspace.fs.stat(vscode.Uri.file(`${gitDir}/${relative}`));
          return true;
        } catch {
          return false;
        }
      };
  
      const shortenRef = async (value?: string): Promise<string | undefined> => {
        if (!value) {
          return undefined;
        }
        try {
          const result = await this.runGit(['rev-parse', '--short', value]);
          return result.stdout.trim() || value.slice(0, 8);
        } catch {
          return value.slice(0, 8);
        }
      };
  
      // Run all existence checks in parallel to avoid sequential FS round-trips.
      // On Windows each stat goes through Defender; sequential calls add up to 50-250 ms.
      const [hasMergeRebase, hasApplyRebase, hasMergeHead, hasCherryPick, hasRevert] =
        await Promise.all([
          exists('rebase-merge'),
          exists('rebase-apply'),
          exists('MERGE_HEAD'),
          exists('CHERRY_PICK_HEAD'),
          exists('REVERT_HEAD')
        ]);
  
      // Rebase: interactive/merge backend
      if (hasMergeRebase) {
        const [head, onto, msgnum, end] = await Promise.all([
          readFile('rebase-merge/head-name'),
          readFile('rebase-merge/onto'),
          readFile('rebase-merge/msgnum'),
          readFile('rebase-merge/end')
        ]);
        return {
          kind: 'rebase',
          headShort: head?.replace(/^refs\/heads\//, ''),
          ontoShort: await shortenRef(onto),
          stepCurrent: msgnum ? Number(msgnum) : undefined,
          stepTotal: end ? Number(end) : undefined
        };
      }
  
      // Rebase: apply backend
      if (hasApplyRebase) {
        const [head, onto, next, last] = await Promise.all([
          readFile('rebase-apply/head-name'),
          readFile('rebase-apply/onto'),
          readFile('rebase-apply/next'),
          readFile('rebase-apply/last')
        ]);
        return {
          kind: 'rebase',
          headShort: head?.replace(/^refs\/heads\//, ''),
          ontoShort: await shortenRef(onto),
          stepCurrent: next ? Number(next) : undefined,
          stepTotal: last ? Number(last) : undefined
        };
      }
  
      if (hasMergeHead) {
        const [mergeHead, mergeMsg] = await Promise.all([
          readFile('MERGE_HEAD'),
          readFile('MERGE_MSG')
        ]);
        return {
          kind: 'merge',
          headShort: await shortenRef(mergeHead?.split('\n')[0]),
          message: mergeMsg?.split('\n')[0]
        };
      }
  
      if (hasCherryPick) {
        const head = await readFile('CHERRY_PICK_HEAD');
        return { kind: 'cherry-pick', headShort: await shortenRef(head) };
      }
  
      if (hasRevert) {
        const head = await readFile('REVERT_HEAD');
        return { kind: 'revert', headShort: await shortenRef(head) };
      }
  
      return { kind: 'none' };
}
