// Generated by split-class.mjs
import type { GitService } from './index';
import { WorktreePruneEntry } from '../../types';
import { parseWorktreePruneDryRun } from '../worktreeParsing';

export async function getPrunableWorktrees(this: GitService): Promise<WorktreePruneEntry[]> {
  const result = await this.runGit(['worktree', 'prune', '--dry-run']);
      return parseWorktreePruneDryRun(result.stdout + result.stderr);
}
