// Generated by split-class.mjs
import type { GitService } from './index';

export async function getPatchForCommitRange(this: GitService, shas: string[]): Promise<string> {
  if (shas.length === 0) {
        return '';
      }
      const result = await this.runGit([
        'format-patch',
        '--stdout',
        `${shas[0]}^..${shas[shas.length - 1]}`
      ]);
      return result.stdout;
}
