// Generated by split-class.mjs
import type { GitService } from './index';

export async function getPatchBetweenWorkingTreeAndRefForFiles(this: GitService, ref: string, filePaths: string[]): Promise<string> {
  if (filePaths.length === 0) {
        return '';
      }
  
      const trackedResult = await this.runGit(['diff', '--binary', ref, '--', ...filePaths]);
      const untrackedResult = await this.runGit([
        'ls-files',
        '--others',
        '--exclude-standard',
        '-z',
        '--',
        ...filePaths
      ]);
      const untrackedPaths = untrackedResult.stdout
        .split('\0')
        .map((value) => value.trim())
        .filter(Boolean);
  
      const patches = [trackedResult.stdout];
      for (const filePath of untrackedPaths) {
        const result = await this.runGitAllowExitCodes(
          ['diff', '--binary', '--no-index', '--', '/dev/null', filePath],
          [0, 1]
        );
        patches.push(result.stdout);
      }
  
      return patches.filter((part) => part.trim()).join('\n');
}
