// Generated by split-class.mjs
import type { GitService } from './index';

export async function getPatchForCommit(this: GitService, sha: string): Promise<string> {
  const result = await this.runGit(['format-patch', '--stdout', '-1', sha]);
      return result.stdout;
}
