// Generated by split-class.mjs
import type { GitService } from './index';

export async function getPatchBetweenRefsForFiles(this: GitService, fromRef: string, toRef: string, filePaths: string[]): Promise<string> {
  if (filePaths.length === 0) {
        return '';
      }
  
      const result = await this.runGit(['diff', '--binary', fromRef, toRef, '--', ...filePaths]);
      return result.stdout;
}
