// Generated by split-class.mjs
import type { GitService } from './index';

export async function getParentCommit(this: GitService, sha: string): Promise<string | undefined> {
  const result = await this.runGit(['rev-list', '--parents', '-n', '1', sha]);
      const tokens = result.stdout.trim().split(/\s+/).filter(Boolean);
  
      if (tokens.length < 2) {
        return undefined;
      }
  
      return tokens[1];
}
