// Generated by split-class.mjs
import type { GitService } from './index';

export async function getPatchForCommitFiles(this: GitService, sha: string, filePaths: string[]): Promise<string> {
  if (filePaths.length === 0) {
        return '';
      }
  
      const result = await this.runGit(['show', '--binary', '--format=', sha, '--', ...filePaths]);
      return result.stdout;
}
