// Generated by split-class.mjs
import { GitService } from './index';
import { BranchRef } from '../../types';
const RECORD_SEPARATOR = '|#|';

export async function getRemoteBranches(this: GitService, remoteUrls: Map<string, string>): Promise<BranchRef[]> {
  const result = await this.runGit([
        'for-each-ref',
        `--format=${GitService.BRANCH_FORMAT}${RECORD_SEPARATOR}`,
        'refs/remotes'
      ]);
      return this.parseBranchLines(result.stdout, remoteUrls).sort(GitService.BRANCH_SORT_COMPARATOR);
}
