// Generated by split-class.mjs
import type { GitService } from './index';

export async function getSubmodulePointerDiff(this: GitService, submodulePath: string): Promise<string> {
  return this.submoduleSvc.getSubmodulePointerDiff(submodulePath);
}
