// Generated by split-class.mjs
import type { GitService } from './index';

export async function getStashPatch(this: GitService, ref: string): Promise<string> {
  const result = await this.runGit(['stash', 'show', '-p', ref]);
      return result.stdout;
}
