// Generated by split-class.mjs
import type { GitService } from './index';

export async function getStagedFiles(this: GitService): Promise<string[]> {
  const result = await this.runGit(['diff', '--cached', '--name-only']);
      return result.stdout
        .split('\n')
        .map((line) => line.trim())
        .filter(Boolean);
}
