// Generated by split-class.mjs
import type { GitService } from './index';
import { SubmoduleEntry } from '../../types';

export async function getSubmodules(this: GitService): Promise<SubmoduleEntry[]> {
  return this.submoduleSvc.getSubmodules();
}
