// Generated by split-class.mjs
import type { GitService } from './index';
import { TagRef } from '../../types';

export async function getTags(this: GitService): Promise<TagRef[]> {
  const [basic, availability] = await Promise.all([
        this.getTagsBasic(),
        this.getTagAvailabilityByRemote()
      ]);
      return this.mergeTagAvailability(basic, availability);
}
