// Generated by split-class.mjs
import { GitService } from './index';
import { TagRef } from '../../types';
const FIELD_SEPARATOR = '|~|';
const RECORD_SEPARATOR = '|#|';

export async function getTagsBasic(this: GitService): Promise<TagRef[]> {
  const result = await this.runGit([
        'for-each-ref',
        `--format=${GitService.TAG_FORMAT}${RECORD_SEPARATOR}`,
        'refs/tags'
      ]);
      return result.stdout
        .split(RECORD_SEPARATOR)
        .map((line) => line.trim())
        .filter(Boolean)
        .map((line) => {
          const [name, fullName, objectSha, peeledSha, commitEpochRaw] = line.split(FIELD_SEPARATOR);
          const commitEpoch = Number.parseInt((commitEpochRaw ?? '').trim(), 10);
          return {
            name,
            fullName,
            sha: peeledSha || objectSha || undefined,
            availableOnRemotes: [] as string[],
            lastCommitEpoch: Number.isNaN(commitEpoch) ? undefined : commitEpoch
          };
        })
        .sort(GitService.TAG_SORT_COMPARATOR);
}
