// Generated by split-class.mjs
import type { GitService } from './index';

export async function getTotalCommitCount(this: GitService): Promise<number> {
  try {
    const result = await this.runGit(['rev-list', '--count', '--all']);
    const count = parseInt(result.stdout.trim(), 10);
    return Number.isFinite(count) ? count : 0;
  } catch {
    return 0;
  }
}
