// Generated by split-class.mjs
import type { GitService } from './index';
import * as vscode from 'vscode';
interface VsCodeGitRepository {
  readonly rootUri: vscode.Uri;
  readonly state: {
    readonly HEAD?: {
      readonly name?: string;
      readonly commit?: string;
    };
    readonly indexChanges: readonly VsCodeGitChange[];
    readonly mergeChanges: readonly VsCodeGitChange[];
    readonly workingTreeChanges: readonly VsCodeGitChange[];
    readonly untrackedChanges: readonly VsCodeGitChange[];
    readonly onDidChange?: vscode.Event<void>;
  };
  status(): Promise<void>;
  add(paths: string[]): Promise<void>;
  restore(paths: string[], options?: { staged?: boolean; ref?: string }): Promise<void>;
  revert(paths: string[]): Promise<void>;
  clean(paths: string[]): Promise<void>;
  createBranch(name: string, checkout: boolean, ref?: string): Promise<void>;
  deleteBranch(name: string, force?: boolean): Promise<void>;
  setBranchUpstream(name: string, upstream: string): Promise<void>;
  checkout(treeish: string): Promise<void>;
  tag(name: string, message: string, ref?: string): Promise<void>;
  fetch(options?: { prune?: boolean }): Promise<void>;
  pull(unshallow?: boolean): Promise<void>;
  push(remoteName?: string, branchName?: string, setUpstream?: boolean): Promise<void>;
  commit(message: string, opts?: { all?: boolean | 'tracked'; amend?: boolean }): Promise<void>;
  rebase(branch: string): Promise<void>;
  mergeAbort(): Promise<void>;
  createStash(options?: {
    message?: string;
    includeUntracked?: boolean;
    staged?: boolean;
  }): Promise<void>;
}
interface VsCodeGitChange {
  readonly uri: vscode.Uri;
}

export async function getVsCodeRepository(this: GitService): Promise<VsCodeGitRepository | undefined> {
  const rootUri = vscode.Uri.file(this.gitRoot);
      if (
        this._vscodeGitRepository &&
        this.samePath(this._vscodeGitRepository.rootUri.fsPath, rootUri.fsPath)
      ) {
        return this._vscodeGitRepository;
      }
  
      const api = await this.getVsCodeGitApi();
      if (!api) {
        return undefined;
      }
  
      const repository =
        api.getRepository(rootUri) ??
        api.repositories.find((candidate) =>
          this.samePath(candidate.rootUri.fsPath, rootUri.fsPath)
        ) ??
        (await api.openRepository(rootUri));
      if (!repository) {
        return undefined;
      }
  
      this._vscodeGitRepository = repository;
      return repository;
}
