// Generated by split-class.mjs
import type { GitService } from './index';

export async function getVsCodeGitRoot(this: GitService): Promise<string | undefined> {
  try {
        const api = await this.getVsCodeGitApi();
        const rootUri = await api?.getRepositoryRoot(this.context.rootUri);
        return rootUri?.fsPath;
      } catch {
        return undefined;
      }
}
