// Generated by split-class.mjs
import type { GitService } from './index';
import { SpawnGitStreamingResult } from '../submoduleService';
import { SubmoduleLogSink } from '../submoduleLogSink';

export async function initAllSubmodules(this: GitService, opts: { sink?: SubmoduleLogSink; signal?: AbortSignal } = {}): Promise<SpawnGitStreamingResult> {
  return this.submoduleSvc.initAllSubmodules(opts);
}
