// Generated by split-class.mjs
import type { GitService } from './index';
import { SpawnGitStreamingResult } from '../submoduleService';
import { SubmoduleLogSink } from '../submoduleLogSink';

export async function initSubmodule(this: GitService, submodulePath: string, opts: { sink?: SubmoduleLogSink; signal?: AbortSignal } = {}): Promise<SpawnGitStreamingResult> {
  return this.submoduleSvc.initSubmodule(submodulePath, opts);
}
