// Generated by split-class.mjs
import type { GitService } from './index';

export async function isCommitInCurrentBranch(this: GitService, sha: string): Promise<boolean> {
  try {
        await this.runGit(['merge-base', '--is-ancestor', sha, 'HEAD']);
        return true;
      } catch {
        return false;
      }
}
