// Generated by split-class.mjs
import type { GitService } from './index';

export async function isPatchAlreadyApplied(this: GitService, patch: string): Promise<boolean> {
  if (!patch.trim()) {
        return false;
      }
  
      try {
        await this.runGitWithStdin(['apply', '--check', '--reverse', '--whitespace=nowarn'], patch);
        return true;
      } catch {
        return false;
      }
}
