// Generated by split-class.mjs
import type { GitService } from './index';

export async function lockWorktree(this: GitService, worktreePath: string, reason?: string): Promise<void> {
  const args = ['worktree', 'lock', worktreePath];
      if (reason) {
        args.push('--reason', reason);
      }
      await this.runGit(args);
}
