// Generated by split-class.mjs
import type { GitService } from './index';
import { getConfigValue } from '../../configuration';

export function logGitDuration(this: GitService, command: string, startedAt: number): void {
  const shouldLog = getConfigValue<boolean>('performance.logGitCommands', false);
      const durationMs = Date.now() - startedAt;
      if (shouldLog && durationMs >= 500) {
        this.logger.info(`[perf] git command took ${durationMs}ms: ${command}`);
      }
}
