// Generated by split-class.mjs
import type { GitService } from './index';
import { TagRef } from '../../types';

export function mergeTagAvailability(this: GitService, tags: readonly TagRef[], availability: ReadonlyMap<string, ReadonlySet<string>>): TagRef[] {
  return tags.map((tag) => ({
        ...tag,
        availableOnRemotes: Array.from(availability.get(tag.name) ?? []).sort((a, b) =>
          a.localeCompare(b)
        )
      }));
}
