// Generated by split-class.mjs
import type { GitService } from './index';

export async function mergeIntoCurrent(this: GitService, branch: string): Promise<void> {
  await this.runGit(['merge', '--no-ff', branch]);
}
