// Generated by split-class.mjs
import type { GitService } from './index';
import * as vscode from 'vscode';

export async function mergeAbort(this: GitService): Promise<void> {
  const repository = await this.getVsCodeRepository();
      if (repository) {
        this.logger.info('vscode.git mergeAbort');
        await repository.mergeAbort();
        return;
      }
      await this.runGit(['merge', '--abort']);
}
