// Generated by split-class.mjs
import type { GitService } from './index';
import * as vscode from 'vscode';

export async function onRepositoryClosed(this: GitService, listener: () => void): Promise<vscode.Disposable | undefined> {
  const api = await this.getVsCodeGitApi();
      if (!api?.onDidCloseRepository) {
        return undefined;
      }
      return api.onDidCloseRepository((repo) => {
        if (this.samePath(repo.rootUri.fsPath, this.gitRoot)) {
          this._vscodeGitRepository = undefined;
          listener();
        }
      });
}
