// Generated by split-class.mjs
import type { GitService } from './index';
import * as vscode from 'vscode';
import { buildRepositoryFingerprint, diffRepositoryFingerprints, isEmptyChangeSet, RepoChangeSet, RepositoryFingerprint } from '../repositoryStateDiff';

export async function onRepositoryStateChange(this: GitService, listener: (changeSet: RepoChangeSet) => void): Promise<vscode.Disposable | undefined> {
  const repository = await this.getVsCodeRepository();
      if (!repository?.state.onDidChange) {
        return undefined;
      }
      let last: RepositoryFingerprint = buildRepositoryFingerprint(repository.state);
      return repository.state.onDidChange(() => {
        const next = buildRepositoryFingerprint(repository.state);
        const changeSet = diffRepositoryFingerprints(last, next);
        last = next;
        if (isEmptyChangeSet(changeSet)) {
          return;
        }
        listener(changeSet);
      });
}
