// Generated by split-class.mjs
import type { GitService } from './index';
import * as vscode from 'vscode';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

export async function openMergeEditor(this: GitService, filePath: string): Promise<void> {
  const outputUri = vscode.Uri.file(path.join(this.gitRoot, filePath));
      try {
        const [base, ours, theirs] = await Promise.all([
          this.getFileStageContent(1, filePath),
          this.getFileStageContent(2, filePath),
          this.getFileStageContent(3, filePath)
        ]);
  
        const tmpDir = os.tmpdir();
        const safe = path.basename(filePath).replace(/[^a-zA-Z0-9._-]/g, '_');
        const writeTemp = (suffix: string, content: string): vscode.Uri => {
          const tmpPath = path.join(tmpDir, `vscodegitclient_${safe}_${suffix}`);
          fs.writeFileSync(tmpPath, content, 'utf8');
          return vscode.Uri.file(tmpPath);
        };
  
        await vscode.commands.executeCommand('mergeEditor.openInput', {
          base: { uri: writeTemp('base', base), title: 'Base' },
          input1: {
            uri: writeTemp('ours', ours),
            title: 'Yours (Current Branch)',
            description: filePath
          },
          input2: {
            uri: writeTemp('theirs', theirs),
            title: 'Theirs (Incoming)',
            description: filePath
          },
          output: outputUri
        });
        await this.applyMergeEditorColumnLayout();
      } catch {
        await vscode.commands.executeCommand('vscode.openWith', outputUri, 'mergeEditor');
        await this.applyMergeEditorColumnLayout();
      }
}
