// Generated by split-class.mjs
import type { GitService } from './index';
import * as vscode from 'vscode';

export async function push(this: GitService): Promise<void> {
  const repository = await this.getVsCodeRepository();
      if (repository) {
        this.logger.info('vscode.git push');
        await repository.push();
        return;
      }
      await this.runGit(['push']);
}
