// Generated by split-class.mjs
import type { GitService } from './index';

export async function rebaseCurrentOnto(this: GitService, branch: string): Promise<void> {
  await this.runGit(['rebase', branch]);
}
