// Generated by split-class.mjs
import type { GitService } from './index';

export async function rebaseContinue(this: GitService): Promise<void> {
  await this.runGit(['-c', 'core.editor=true', 'rebase', '--continue']);
}
