// Generated by split-class.mjs
import type { GitService } from './index';

export async function rebaseInteractive(this: GitService, base: string): Promise<void> {
  await this.runGit(['rebase', '-i', base]);
}
