// Generated by split-class.mjs
import type { GitService } from './index';

export async function refExists(this: GitService, ref: string): Promise<boolean> {
  try {
        await this.runGit(['show-ref', '--verify', '--quiet', ref]);
        return true;
      } catch {
        return false;
      }
}
