// Generated by split-class.mjs
import type { GitService } from './index';

export async function refPatternExists(this: GitService, pattern: string): Promise<boolean> {
  const result = await this.runGit(['for-each-ref', '--format=%(refname)', pattern]);
      return result.stdout.trim().length > 0;
}
