// Generated by split-class.mjs
import type { GitService } from './index';

export async function removeWorktree(this: GitService, worktreePath: string, force = false): Promise<void> {
  const args = ['worktree', 'remove', worktreePath];
      if (force) {
        args.push('--force');
      }
      await this.runGit(args);
}
