// Generated by split-class.mjs
import type { GitService } from './index';

export async function renameStash(this: GitService, ref: string, message: string): Promise<void> {
  const stashHash = (await this.runGit(['rev-parse', ref])).stdout.trim();
      await this.runGit(['stash', 'drop', ref]);
      await this.runGit(['stash', 'store', '-m', message, stashHash]);
}
