// Generated by split-class.mjs
import type { GitService } from './index';

export async function renameBranch(this: GitService, from: string, to: string): Promise<void> {
  await this.runGit(['branch', '-m', from, to]);
}
