// Generated by split-class.mjs
import type { GitService } from './index';

export async function resetCurrent(this: GitService, ref: string, mode: 'soft' | 'mixed' | 'hard'): Promise<void> {
  await this.runGit(['reset', `--${mode}`, ref]);
}
