// Generated by split-class.mjs
import type { GitService } from './index';

export async function resolveConflictOurs(this: GitService, path: string): Promise<void> {
  await this.runGit(['checkout', '--ours', '--', path]);
      await this.runGit(['add', '--', path]);
}
