// Generated by split-class.mjs
import type { GitService } from './index';

export async function resolveConflictTheirs(this: GitService, path: string): Promise<void> {
  await this.runGit(['checkout', '--theirs', '--', path]);
      await this.runGit(['add', '--', path]);
}
