// Generated by split-class.mjs
import type { GitService } from './index';

export async function reverseApplyPatchToWorkingTree(this: GitService, patch: string): Promise<void> {
  if (!patch.trim()) {
        return;
      }
  
      await this.runGitWithStdin(['apply', '--3way', '--whitespace=nowarn', '-R'], patch);
}
