// Generated by split-class.mjs
import type { GitService } from './index';

export async function revertCommitFiles(this: GitService, ref: string, filePaths: string[]): Promise<void> {
  await this.applyCommitFilesPatch(ref, filePaths, true);
}
