// Generated by split-class.mjs
import type { GitService } from './index';
import { getConfigValue } from '../../configuration';
import { GitCommandResult } from '../../types';
import * as cp from 'child_process';

export async function runGitAllowExitCodes(this: GitService, args: string[], allowedExitCodes: readonly number[]): Promise<GitCommandResult> {
  const gitPath = getConfigValue<string>('gitPath', 'git');
      const timeoutMs = getConfigValue<number>('commandTimeoutMs', 15000);
      const command = `${gitPath} ${args.join(' ')}`;
      this.logger.info(`git ${args.join(' ')}`);
  
      return this.gitCommandQueue.run(
        () =>
          new Promise<GitCommandResult>((resolve, reject) => {
            const startedAt = Date.now();
            const child = cp.spawn(gitPath, args, {
              cwd: this.gitRoot,
              windowsHide: true
            });
  
            const timer = setTimeout(() => {
              child.kill();
              this.logGitDuration(command, startedAt);
              reject(new Error(`Git command timed out after ${timeoutMs}ms: ${command}`));
            }, timeoutMs);
  
            let stdout = '';
            let stderr = '';
  
            child.stdout.on('data', (chunk) => {
              stdout += chunk.toString();
            });
  
            child.stderr.on('data', (chunk) => {
              stderr += chunk.toString();
            });
  
            child.on('error', (error) => {
              clearTimeout(timer);
              this.logGitDuration(command, startedAt);
              reject(error);
            });
  
            child.on('close', (code) => {
              clearTimeout(timer);
              this.logGitDuration(command, startedAt);
              if (code !== null && allowedExitCodes.includes(code)) {
                resolve({ stdout, stderr });
                return;
              }
  
              const error = new Error(
                stderr || `Git command failed with exit code ${code}: ${command}`
              );
              reject(error);
            });
          })
      );
}
