// Generated by split-class.mjs
import type { GitService } from './index';
import * as path from 'path';

export function samePath(this: GitService, left: string, right: string): boolean {
  const normalizedLeft = path.normalize(left);
      const normalizedRight = path.normalize(right);
      return process.platform === 'win32'
        ? normalizedLeft.toLowerCase() === normalizedRight.toLowerCase()
        : normalizedLeft === normalizedRight;
}
