// Generated by split-class.mjs
import type { GitService } from './index';

export async function setRemoteUrl(this: GitService, remoteName: string, remoteUrl: string): Promise<void> {
  await this.runGit(['remote', 'set-url', remoteName, remoteUrl]);
}
