// Generated by split-class.mjs
import type { GitService } from './index';

export async function stageSubmodulePointer(this: GitService, submodulePath: string): Promise<void> {
  return this.submoduleSvc.stageSubmodulePointer(submodulePath);
}
