// Generated by split-class.mjs
import type { GitService } from './index';

export async function stagePatch(this: GitService, filePath: string): Promise<void> {
  await this.runGit(['add', '-p', '--', filePath]);
}
