// Generated by split-class.mjs
import type { GitService } from './index';
import * as vscode from 'vscode';

export async function stageFile(this: GitService, path: string): Promise<void> {
  const repository = await this.getVsCodeRepository();
      if (repository) {
        this.logger.info(`vscode.git add ${path}`);
        await repository.add([this.toAbsoluteRepoPath(path)]);
        return;
      }
      await this.runGit(['add', '--', path]);
}
