// Generated by split-class.mjs
import type { GitService } from './index';
import { getConfigValue } from '../../configuration';
import { GraphCommit } from '../../types';
import * as cp from 'child_process';
const RECORD_SEPARATOR = '|#|';
function parseGraphRows(raw: string): GraphCommit[] {
  return raw
    .split(RECORD_SEPARATOR)
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => {
      const [graph, sha, shortSha, parentsRaw, refsRaw, author, date, subject] =
        line.split(FIELD_SEPARATOR);
      return {
        graph,
        sha,
        shortSha,
        parents: parentsRaw?.split(' ').filter(Boolean) ?? [],
        refs: refsRaw
          ? refsRaw
              .split(',')
              .map((r) => r.trim())
              .filter(Boolean)
          : [],
        author,
        date,
        subject
      };
    });
}
const FIELD_SEPARATOR = '|~|';

export function streamLogRecords(this: GitService, args: string[], onBatch: (commits: GraphCommit[]) => void): Promise<GraphCommit[]> {
  const gitPath = getConfigValue<string>('gitPath', 'git');
      const idleTimeoutMs = getConfigValue<number>('commandTimeoutMs', 15000);
      const command = `${gitPath} ${args.join(' ')}`;
      this.logger.info(`git ${args.join(' ')}`);
  
      const BATCH_SIZE = 25;
      const FLUSH_INTERVAL_MS = 80;
  
      return this.gitCommandQueue.run(
        () =>
          new Promise<GraphCommit[]>((resolve, reject) => {
            const startedAt = Date.now();
            const child = cp.spawn(gitPath, args, {
              cwd: this.gitRoot,
              windowsHide: true
            });
  
            const all: GraphCommit[] = [];
            let pending: GraphCommit[] = [];
            let buffer = '';
            let stderr = '';
            let flushTimer: NodeJS.Timeout | null = null;
            let idleTimer: NodeJS.Timeout | null = null;
  
            const clearTimers = (): void => {
              if (flushTimer) {
                clearTimeout(flushTimer);
                flushTimer = null;
              }
              if (idleTimer) {
                clearTimeout(idleTimer);
                idleTimer = null;
              }
            };
  
            // Idle timeout: only fires when git has produced no output for
            // `idleTimeoutMs`. A continuously streaming git log never trips it, so
            // the total wall-clock time is unbounded — fine because we surface
            // commits as they arrive.
            const resetIdleTimer = (): void => {
              if (idleTimer) {
                clearTimeout(idleTimer);
              }
              idleTimer = setTimeout(() => {
                child.kill();
                this.logGitDuration(command, startedAt);
                clearTimers();
                reject(new Error(`Git command idle for ${idleTimeoutMs}ms: ${command}`));
              }, idleTimeoutMs);
            };
  
            const flush = (): void => {
              if (flushTimer) {
                clearTimeout(flushTimer);
                flushTimer = null;
              }
              if (pending.length === 0) {
                return;
              }
              const batch = pending;
              pending = [];
              all.push(...batch);
              try {
                onBatch(batch);
              } catch (err) {
                this.logger.info(
                  `directoryHistory onBatch error: ${err instanceof Error ? err.message : String(err)}`
                );
              }
            };
  
            const scheduleFlush = (): void => {
              if (pending.length >= BATCH_SIZE) {
                flush();
                return;
              }
              if (flushTimer === null) {
                flushTimer = setTimeout(flush, FLUSH_INTERVAL_MS);
              }
            };
  
            const consumeBuffer = (): void => {
              let sepIndex = buffer.indexOf(RECORD_SEPARATOR);
              while (sepIndex !== -1) {
                const record = buffer.slice(0, sepIndex).trim();
                buffer = buffer.slice(sepIndex + RECORD_SEPARATOR.length);
                if (record) {
                  const parsed = parseGraphRows(record + RECORD_SEPARATOR);
                  if (parsed.length > 0) {
                    pending.push(...parsed);
                  }
                }
                sepIndex = buffer.indexOf(RECORD_SEPARATOR);
              }
              if (pending.length > 0) {
                scheduleFlush();
              }
            };
  
            resetIdleTimer();
  
            child.stdout.on('data', (chunk: Buffer) => {
              resetIdleTimer();
              buffer += chunk.toString();
              consumeBuffer();
            });
  
            child.stderr.on('data', (chunk: Buffer) => {
              resetIdleTimer();
              stderr += chunk.toString();
            });
  
            child.on('error', (error: Error) => {
              clearTimers();
              this.logGitDuration(command, startedAt);
              reject(error);
            });
  
            child.on('close', (code: number | null) => {
              clearTimers();
              this.logGitDuration(command, startedAt);
              if (code !== 0) {
                reject(new Error(stderr || `Git command failed with exit code ${code}: ${command}`));
                return;
              }
              // Drain any trailing record without a separator (defensive — format ends with separator).
              const tail = buffer.trim();
              if (tail) {
                const parsed = parseGraphRows(tail + RECORD_SEPARATOR);
                if (parsed.length > 0) {
                  pending.push(...parsed);
                }
              }
              flush();
              resolve(all);
            });
          })
      );
}
