// Generated by split-class.mjs
import type { GitService } from './index';
import * as path from 'path';

export function toAbsoluteRepoPath(this: GitService, relativeOrAbsolutePath: string): string {
  return path.isAbsolute(relativeOrAbsolutePath)
        ? relativeOrAbsolutePath
        : path.join(this.gitRoot, relativeOrAbsolutePath);
}
