// Generated by split-class.mjs
import type { GitService } from './index';
import * as path from 'path';

export function toRepoRelative(this: GitService, absolutePath: string): string | undefined {
  const rel = path.relative(this.gitRoot, absolutePath);
      if (!rel || rel.startsWith('..') || path.isAbsolute(rel)) {
        return undefined;
      }
      return rel.split(path.sep).join('/');
}
