// Generated by split-class.mjs
import type { GitService } from './index';
interface VsCodeGitChange {
  readonly uri: vscode.Uri;
}
import * as vscode from 'vscode';

export function uniqueChangePaths(this: GitService, changes: readonly VsCodeGitChange[]): string[] {
  return [...new Set(changes.map((change) => change.uri.fsPath))];
}
