// Generated by split-class.mjs
import type { GitService } from './index';

export async function unlockWorktree(this: GitService, worktreePath: string): Promise<void> {
  await this.runGit(['worktree', 'unlock', worktreePath]);
}
