// Generated by split-class.mjs
import type { GitService } from './index';
import * as vscode from 'vscode';

export async function unstageFile(this: GitService, path: string): Promise<void> {
  const repository = await this.getVsCodeRepository();
      if (repository) {
        this.logger.info(`vscode.git restore --staged ${path}`);
        await repository.restore([this.toAbsoluteRepoPath(path)], { staged: true });
        return;
      }
      await this.runGit(['restore', '--staged', '--', path]);
}
