// Generated by split-class.mjs
import type { GitService } from './index';

export async function unstashToWorkingTree(this: GitService, ref: string): Promise<void> {
  await this.runGit(['stash', 'pop', ref]);
}
