// Generated by split-class.mjs
import type { GitService } from './index';

export async function untrackBranch(this: GitService, localBranch: string): Promise<void> {
  await this.runGit(['branch', '--unset-upstream', localBranch]);
}
