// Generated by split-class.mjs
import type { GitService } from './index';
import { SpawnGitStreamingResult } from '../submoduleService';
import { SubmoduleLogSink } from '../submoduleLogSink';

export async function updateAllSubmodules(this: GitService, recursive = false, opts: { sink?: SubmoduleLogSink; signal?: AbortSignal } = {}): Promise<SpawnGitStreamingResult> {
  return this.submoduleSvc.updateAllSubmodules(recursive, opts);
}
